
var  zh_hans = {
  user_login:'User Login',
  user_name:'User Name',
  placeholder_user_name:'Please enter your username',
  please_choose:'Please choose',
  password:'Password',
  forget_password:'Forget password?',
  login:'Sign in',
  reset_password:'Reset password',
  placeholder_validation_code:'Please enter the validation code: ',
  cancel:'Cancel',
  sure:'OK',
  // new_password:'New password',
  // confirm_password:'确认密码',
  // condition_title:'密码必须满足以下条件：',
  // password_length:'密码长度为',
  // to_16:'至 16 位；',
  // two_characters:'必须包含两种字符（数字、大写字母、小写字母、特殊字符）；',
  // three_characters:'必须包含三种字符（数字、大写字母、小写字母、特殊字符）；',
  // four_characters:'必须包含四种字符（数字、大写字母、小写字母、特殊字符）；',
  // continues_three:'连续3位及以上数字不能连号（例如：123、654）；',
  // not_contains:'密码不能包含账号；',
  // not_contain_name:'密码不能包含用户姓名大小写全拼；',
  // not_continuous_letters:'连续3位及以上字母不能连号（例如：abc、cba）；',
  // consecutive_identical_characters:'密码不能包含连续3个及以上相同字符（例如：aaa、rrr）；',


  // 通用
  MONDAY: "Monday",
  TUESDAY: "Tuesday",
  WEDNESDAY: "Wednesday",
  THURSDAY: "Thursday",
  FRIDAY: "Friday",
  SATURDAY: "Saturday",
  SUNDAY: "Sunday",
  USERNAME: "Username",
  PASSWORD: "Password",
  ADDRBOOK_HIDE: "Hide contacts",
  ADDRBOOK_SHOW: "Open contacts",
  COMMON_BUTTON_ALTER: "Edit",
  COMMON_BUTTON_SAVE: "Save",
  COMMON_BUTTON_CANCELL: "Cancel",
  COMMON_BUTTON_CONFIRM: "OK",
  COMMON_BUTTON_DELETE: "Delete",
  COMMON_BUTTON_SUBMIT: "Submit",
  COMMON_BUTTON_ADD: "Add",
  COMMON_BUTTON_PREVIEW: "Preview",
  COMMON_BUTTON_ZHAOHUI: "Recall",
  COMMON_CLOSE: "Close",
  COMMON_BUTTON_CONFIRM_SUBMIT: "Confirm submission?",
  COMMON_BUTTON_DELETE_SUBMIT: "Confirm delete?",
  COMMON_BUTTON_DISABLE_SUBMIT: "Confirm disabled?",
  COMMON_BUTTON_ENABLE_SUBMIT: "Confirm enabled?",
  COMMON_BUTTON_CONFIRM_NOTICE: "Infomation",
  COMMON_BUTTON_SYSTEM_NOTICE: "System Infomation",
  COMMON_ALTER_SUCCESS: "Edit Successfully",
  COMMON_ALTER_FAILED: "Edit failed",
  COMMON_SAVE_SUCCESS: "Save Successfully",
  COMMON_SAVE_FAILED: "Save failed",
  COMMON_SUBMIT_SUCCESS: "Submit Successfully",
  COMMON_SUBMIT_FAILED: "Submit failed",
  COMMON_ADD_SUCCESS: "Add Successfully",
  COMMON_ADD_FAILED: "Add failed",
  COMMON_SET_SUCCESS: "Set successfully",
  COMMON_SET_FAILED: "Set failed",
  COMMON_DELETE_SUCCESS: "Delete Successfully",
  COMMON_DELETE_FAILED: "Delete failed",
  COMMON_DISABLE_SUCCESS: "Disabled successfully",
  COMMON_DISABLE_FAILED: "Disabled failed",
  COMMON_ENABLE_SUCCESS: "Enabled successfully",
  COMMON_ENABLE_FAILED: "Enabled failed",
  COMMON_OPRATE_SUCCESS: "Successful operation",
  COMMON_OPRATE_FAILED: "Failure operation",
  COMMON_DOWNLOAD_SUCCESS: "Download successful",
  COMMON_DOWNLOAD_FAILED: "Download failed",
  COMMON_IMPORT_SUCCESS: "Successfully imported",
  COMMON_IMPORT_FAILED: "Failure imported",
  COMMON_EXPORT_SUCCESS: "Export successful",
  COMMON_EXPORT_FAILED: "Export failed",
  COMMON_HOME_NAME: "Home",
  COMMON_SIGNATURA: "Signature",
  COMMON_TEMPLATE: "Template",
  COMMON_NAME: "Name",
  COMMON_OPRATE: "Operation",
  COMMON_TIME: "Time",
  COMMON_PERMISSION: "Permission",
  COMMON_PERMISSION_DESC: "There is no permission to do this for the shared mailbox you are logged into.",
  COMMON_STATUS: "Status",
  COMMON_STATUS_ENABLE: "Enable",
  COMMON_STATUS_DISABLE: "Disable",
  COMMON_STATUS_SHI: "Yes",
  COMMON_STATUS_FOU: "No",
  COMMON_SEARCH: "Search",
  COMMON_SEARCH2: "Search",
  COMMON_SEARCH_DATE: "query date",
  COMMON_SELECT_DATE: "select date",
  COMMON_SUBJECT: "Title",
  COMMON_CONTENT: "Content",
  COMMON_SUBJECT2: "Subject",
  COMMON_MAIL_SUBJECT: "Email Subject",
  COMMON_REMARK: "Remark",
  COMMON_DESCIPTION: "Description",
  COMMON_SIZE: "Size",
  COMMON_SENDER: "Sender",
  COMMON_RECAIVER: "Recipient",
  COMMON_XINGMING: "Name",
  COMMON_EMAIL: "Email",
  COMMON_EMAIL2: "Email",
  COMMON_MOBILE: "Mobile phone",
  COMMON_MOBILE2: "Mobile phone",
  COMMON_BIRTHDAY: "Birthday",
  COMMON_DEPARTMENT: "Department",
  COMMON_POSITION: "Post",
  COMMON_TELGROUP: "Group number",
  COMMON_TELWORK: "Job number",
  COMMON_TELWORKEXT: "Ext",
  COMMON_GENDER: "Gender",
  COMMON_GENDER_M: "Male",
  COMMON_GENDER_F: "Female",
  COMMON_SRC_PASSWORD: "Original password",
  COMMON_NEW_PASSWORD: "New password",
  COMMON_CONFIRM_PASSWORD: "Confirm password",
  COMMON_PASSWORD_NOTICE: "Password must meet the following conditions:",
  COMMON_PASSWORD_NOTICE_1: "Password length ",
  COMMON_PASSWORD_NOTICE_2: " to 16 characters;",
  COMMON_PASSWORD_NOTICE_3: "Must contain two characters (numeric, uppercase, lowercase, special);",
  COMMON_PASSWORD_NOTICE_4: "Must contain three characters (numeric, uppercase, lowercase, special);",
  COMMON_PASSWORD_NOTICE_5: "Must contain four characters (numeric, uppercase, lowercase, special);",
  COMMON_PASSWORD_NOTICE_6: "3 consecutive digits and above cannot be joined (E.g: 123, 654);",
  COMMON_PASSWORD_NOTICE_7: "Password cannot contain account;",
  COMMON_PASSWORD_NOTICE_8: "Password cannot contain the full spelling of the user's name;",
  COMMON_PASSWORD_NOTICE_9: "Letters with 3 or more consecutive digits cannot be joined together (E.g: abc, cba);",
  COMMON_PASSWORD_NOTICE_10: "Password cannot contain 3 consecutive characters or more (E.g: aaa, rrr);",
  COMMON_SRC_PASSWORD_RULE_LEN: "Length must be greater than 1 character",
  COMMON_PASSWORD_RULE_LEN: "Length 8 to 20 characters",
  COMMON_SRC_PASSWORD_RULE: "Please enter original password",
  COMMON_NEW_PASSWORD_RULE: "Please enter new password",
  COMMON_CONFIRM_PASSWORD_RULE: "Please enter confirm password",
  CONMON_PASSWORD_SECURITY_QD1: "My favorite person's name",
  CONMON_PASSWORD_SECURITY_QD2: "My favorite thing",
  CONMON_PASSWORD_SECURITY_QD3: "My favorite movie",
  CONMON_PASSWORD_SECURITY_QD4: "Middle school name",
  CONMON_PASSWORD_SECURITY_QD5: "My favorite song",
  CONMON_PASSWORD_SECURITY_QD6: "My favorite food",
  CONMON_PASSWORD_SECURITY_QD7: "My first love date",
  CONMON_PASSWORD_SECURITY_QD8: "My mother's birthday",
  COMMON_FETCH_VERIFICATION_CODE: "Send SMS",
  COMMON_TWOFACTOR_GOOGLE: "Google Authentication",
  COMMON_TWOFACTOR_PHONE: "SMS Authentication",
  SETTING_RE_ADD_PLACEHODER: "please select",
  COMMON_NODATA: "No data",

  // 文件中心
  FILE_INDEX_P: "Personal Net Folder",
  FILE_INDEX_C: "Enterprise Net Folder ",
  FILE_INDEX_A: "File Transit Center",
  FILE_INDEX_MSG1: "The preview file is larger than 10M, please download and view!",
  FILE_INDEX_MSG2: "Mail delivery cannot contain folders, please re-select!",
  FILE_INDEX_MSG3: "Error previewing file!",
  // 个人网盘
  FILE_P_PRE: "Back",
  FILE_P_UPLOAD: "Upload",
  FILE_P_DOWNLOAD: "Download",
  FILE_P_MOVE: "Move",
  FILE_P_SEND: "Send message",
  FILE_P_SEND2: "Send message",
  FILE_P_FOLDERS: " folders, ",
  FILE_P_FILES: " files.",
  FILE_P_CAP: "Space:",
  FILE_P_SEARCH: "search documents",
  FILE_P_PATH: "Path:",
  FILE_P_RENAME: "Rename",
  FILE_P_TIME: "Time",
  FILE_P_UPPATH: "Upload Path",
  FILE_P_UPPATH2: "Upload Path",
  FILE_P_UPPATH_PLACE: "Please select the upload path",
  FILE_P_MOVEPATH: "Move Path",
  FILE_P_MOVEPATH_PLACE: "Please select the move-to path",
  FILE_P_FILEUPING: "Uploading files, please wait...",
  FILE_P_FILESCAN: "Scanning files...",
  FILE_P_UPSTATUS_SUCCESS: "success",
  FILE_P_UPSTATUS_FAILED: "failure",
  FILE_P_UPSTATUS_UP: "uploading...",
  FILE_P_UPSTATUS_PAUSE: "paused",
  FILE_P_UPSTATUS_WAIT: "waiting",
  FILE_P_YEAR: "year(s)",
  FILE_P_DAY: "day(s)",
  FILE_P_HOUR: "hour(s)",
  FILE_P_MIN: "minute(s)",
  FILE_P_SEC: "second(s)",
  FILE_P_RULE1: "please enter folder name",
  FILE_P_RULE2: "Length 1 to 20 characters",
  FILE_P_RULE3: "My document",
  FILE_P_RULE4: "please enter name",
  FILE_P_RULE5: "please select folder ID",
  FILE_P_SUCCESS: "Upload successful!",
  FILE_P_UPFAILED: "Upload failed!",
  FILE_P_SERVERERR: "Server error!",
  FILE_P_MSG1: "Failed to upload, the uploaded file has exceeded the remaining capacity of personal net disk!",
  FILE_P_MSG2: "Are you sure to move the selected files and folders?",
  FILE_P_MSG3: "Move successfully",
  FILE_P_MSG4: "Are you sure to delete the selected files and folders?",
  FILE_P_MSG5: "Are you sure you want to delete the current file or folder?",
  FILE_P_MSG6: "Are you sure you want to download the current file or folder?",
  FILE_P_MSG7: "Are you sure you want to download the selected files and folders?",
  // 企业网盘
  FILE_C_ADDPERM: "Add permissions",
  FILE_C_MPERM: "Permission management",
  FILE_C_PUTM: "Give network disk administrator",
  FILE_C_VISIT: "Visit",
  FILE_C_SEARCH: "Search:",
  FILE_C_SEARCH2: "please enter keyword",
  FILE_C_PERMDELETE: "Delete permissions",
  FILE_C_UPLOADER: "Uploader",
  FILE_C_PERM_DESC: "Operation permissions:",
  FILE_C_PERM_DESC1: "Operation permissions",
  FILE_C_PERM_DESC2: "competence:",
  FILE_C_PERM_PLACE: "please select permission",
  FILE_C_PERM: "all",
  FILE_C_PERM1: "management",
  FILE_C_PERM2: "upload",
  FILE_C_PERM3: "download",
  FILE_C_PERM4: "upload and download",
  FILE_C_PERM_TITLE: "Give network disk administrator - Network disk administrator has administrative rights to the entire enterprise network disk.",
  FILE_C_PERM_TITLE2: "Network disk administrator has administrative rights to the entire enterprise network disk.",
  FILE_C_OBJNAME: "Department / Member",
  FILE_C_FOLDER: "Folder",
  FILE_C_RULE1: "My document",
  FILE_C_MSG1: "Upload failed! Upload files have exceeded the remaining capacity of enterprise network disk!",
  FILE_C_MSG2: "Edit permissions successfully!",
  FILE_C_MSG3: "Edit permissions failed!",
  FILE_C_MSG4: "Are you sure to delete permissions?",
  FILE_C_MSG5: "Delete permissions successfully!",
  FILE_C_MSG6: "Delete permissions failed!",
  FILE_C_MSG7: "Are you sure to delete the selected permissions?",
  FILE_C_MSG8: "Failed to get permission member list!",
  FILE_C_MSG9: "Give network disk administrator successfully!",
  FILE_C_MSG10: "Give network disk administrator failed!",
  FILE_C_MSG11: "Add permissions successfully!",
  FILE_C_MSG12: "Add permissions failed!",
  FILE_C_MSG13: "please select folder!",
  FILE_C_MSG14: "Move failed, please re-try!",
  // 文件中转站
  FILE_A_TOP: "To Personal Net Folder",
  FILE_A_SEARCH: "Search attachments",
  FILE_A_XUQI: "Renewal",
  FILE_A_TIME: "Valid time",
  FILE_A_PATH: "Path",
  FILE_A_PATH_PLACE: "please select the personal net folder",
  FILE_A_DAY: "day(s)",
  FILE_A_HOUR: "hour(s)",
  FILE_A_MIN: "minute(s)",
  FILE_A_EXP: "will expire",
  FILE_A_NEXP: "forever",
  FILE_A_RULE: "please select the move-to folder",
  FILE_A_MSG1: "Are you sure to delete the selected file?",
  FILE_A_MSG2: "Are you sure to delete the file?",
  FILE_A_MSG3: "Renewed success!",
  FILE_A_MSG4: "Renewed failure!",
  FILE_A_MSG5: "Are you sure to download the attachment?",
  FILE_A_MSG6: "Are you sure to download the selected attachment?",
  FILE_A_MSG7: "Are you sure to save it to your personal network disk?",

  // 联系人
  CONTANCT_INDEX_PAB: "Personal",
  CONTANCT_INDEX_OAB: "Corporate",
  CONTANCT_INDEX_CAB: "Public",
  CONTANCT_INDEX_SOAB: "Other Domain",
  // 个人通讯录
  CONTACT_PAB_TITLE: "Group",
  CONTACT_PAB_ADD: "Add Group",
  CONTACT_PAB_BREADCRUM: "Group：",
  CONTACT_PAB_SEARCH: "email or name",
  CONTACT_PAB_SEARCH2: "Grouping",
  CONTACT_PAB_SEARCH21: "all",
  CONTACT_PAB_SEARCH22: "grouped",
  CONTACT_PAB_SEARCH23: "no group",
  CONTACT_PAB_ADDC: "Add Contact",
  CONTACT_PAB_IMPC: "Import Contacts",
  CONTACT_PAB_EXPC: "Export Contacts",
  CONTACT_PAB_ADDG: "Add To Group",
  CONTACT_PAB_SEND: "Selected and Send Message",
  CONTACT_PAB_SENDG: "Send Message",
  CONTACT_PAB_BDEL: "Delete Contacts",
  CONTACT_PAB_ADD_GTITLE: "Add Group",
  CONTACT_PAB_ALT_GTITLE: "Edit Group",
  CONTACT_PAB_ADD_CTITLE: "Add Contact",
  CONTACT_PAB_ALT_CTITLE: "Edit Contact",
  CONTACT_PAB_ADD_TOGTITLE: "Add selected contacts to contact group",
  CONTACT_PAB_ADD_IGTITLE: "Import Contact",
  CONTACT_PAB_ADD_FILE: "upload file",
  CONTACT_PAB_ADD_IMPTO: "To Group",
  CONTACT_PAB_ADD_IMPMODE: "Repeat address",
  CONTACT_PAB_ADD_IMPMODE1: "ignore",
  CONTACT_PAB_ADD_IMPMODE2: "cover",
  CONTACT_PAB_ADD_G: "Group",
  CONTACT_PAB_WORKTEL: "Business Phone",
  CONTACT_PAB_CONTRY: "Contry",
  CONTACT_PAB_STATE: "Province",
  CONTACT_PAB_JIATING: "Family info",
  CONTACT_PAB_DANWEI: "Company Info",
  CONTACT_PAB_DANWEI_NAME: "Company",
  CONTACT_PAB_FAX: "Business Fax",
  CONTACT_PAB_RULE1: "Please enter group name",
  CONTACT_PAB_RULE2: "Length 1 to 50 characters",
  CONTACT_PAB_RULE3: "Please select group",
  CONTACT_PAB_RULE4: "Please select file",
  CONTACT_PAB_CANCELL: "Undelete",
  CONTACT_PAB_MSG1: "Are you sure to delete the selected contacts completely from All Contacts?",
  CONTACT_PAB_MSG2: "This action removes the contact from All Contacts.",
  CONTACT_PAB_MSG3: "Are you sure to move the selected contact out?",
  CONTACT_PAB_MSG4: "And delete it completely from the address book.",
  CONTACT_PAB_MSG5: "Are you sure to send message to this group?",
  CONTACT_PAB_MSG6: "mailbox not found!",
  CONTACT_PAB_MSG7: "Only xls, xlsx, or csv files can be uploaded! ",
  CONTACT_PAB_MSG8: "File size cannot exceed 10M!",
  CONTACT_PAB_MSG9: "Are you sure to export this group?",
  CONTACT_PAB_MSG10: "Are you sure to this group?",
  // 组织通讯录
  CONTACT_OAB_CUR: "Department:",
  CONTACT_OAB_EXPCF: "Export to Foxmail format",
  CONTACT_OAB_EXPCO: "Export to Outlook format",
  CONTACT_OAB_EXPCT: "Enterprise tutorial of Client",
  CONTACT_OAB_SEND: "Selected And Send Message",
  CONTACT_OAB_SENDO: "Send Message To Department",
  CONTACT_OAB_TOPAB: "Add To Personal Contacts",
  CONTACT_OAB_WORKTEL: "Job No / Ext",
  CONTACT_OAB_MSG1: "Are you sure to export the department contacts?",
  CONTACT_OAB_MSG2: "Are you sure to delete the selected record?",
  CONTACT_OAB_MSG3: "Are you sure to send the email to staff of this department?",
  CONTACT_OAB_MSG4: "Are you sure to add the selected member to your personal contact?",
  CONTACT_OAB_MSG5: "Have successfully added contacts to your personal contact",
  // 公共通讯录
  // 其他域通讯录

  // 自助查询
  // 登录查询
  CENTER_LOGIN: "Login",
  CENTER_LOGIN_TIME: "Login Time",
  CENTER_LOGIN_IP: "IP Address",
  CENTER_LOGIN_AREA: "Login Area",
  CENTER_LOGIN_MODE: "Login Method",
  CENTER_LOGIN_REMARK: "Login result",
  CENTER_LOGIN_BROWSER: "Device/system/browser",
  // 发信查询
  CENTER_SEND: "Send",
  CENTER_SEND_ALLRCP: "All recipients",
  CENTER_SEND_ZHAOHUI_ALL: "Recall All",
  CENTER_SEND_ZHAOHUI_TITLE: "Recall",
  CENTER_SEND_STATUS: "Recall Status",
  CENTER_SEND_DETAIL: "Detail",
  CENTER_SEND_MSG1: "Are you sure to recall?",
  CENTER_SEND_MSG2: "Cancelled recall",
  // 收信查询
  CENTER_RCPT: "Receive",
  CENTER_RCPT_ACT1: "All",
  CENTER_RCPT_ACT2: "Inbox And Personal",
  CENTER_RCPT_ACT3: "Spam",
  CENTER_RCPT_ACT4: "Script Blocking",
  CENTER_RCPT_ACT5: "Spam Blocking",
  CENTER_RCPT_LOC: "Storage location",
  // 删信查询
  CENTER_DELETE: "Delete",
  CENTER_DELETE_ACT1: "All",
  CENTER_DELETE_ACT2: "Deleted by Webmail",
  CENTER_DELETE_ACT3: "Manually deleted",
  CENTER_DELETE_ACT4: "Deleted by Client",
  CENTER_DELETE_TIME: "Delete Time",
  CENTER_DELETE_SENDER: "Sender/operator",
  CENTER_DELETE_INFO: "Deleted Information",
  CENTER_DELETE_LOC: "Deleted location",

  // 设置页面
  SETTING_INDEX_NAME: "Setting",
  SETTING_INDEX_PERSONAL_MENU: "Personal data",
  SETTING_INDEX_PASSWORD_MENU: "Password",
  SETTING_INDEX_PASSWORD_MENU_TITLE: "Reset password",
  SETTING_INDEX_TWOFACTOR_MENU: "Security",
  SETTING_INDEX_PARAM_MENU: "Parameter",
  SETTING_INDEX_PARAM_MENU_TITLE: "Setup some displayed parameters of email receiving and sending",
  SETTING_INDEX_SKIN_MENU: "Skin Center",
  SETTING_INDEX_RE_MENU: "Auto Reply",
  SETTING_INDEX_FW_MENU: "Auto Forwarded",
  SETTING_INDEX_WHITE_MENU: "White List",
  SETTING_INDEX_WHITE_MENU_TITLE: "Manage the white list to unimpede friend emails",
  SETTING_INDEX_BLACK_MENU: "Black List",
  SETTING_INDEX_BLACK_MENU_TITLE: "Setup black list to filter the junk email automatically",
  SETTING_INDEX_MOVE_MENU: "Mailbox Moving",
  SETTING_INDEX_MOVE_MENU_TITLE: "Migrate mail data from other mailboxes",
  SETTING_INDEX_SMS_MENU: "SMS Notification",
  SETTING_INDEX_FEEDBACK_MENU: "Feedback",
  SETTING_INDEX_ZHAOHUI_MENU: "Recall data",
  SETTING_INDEX_FILTER_MENU: "Filter",
  SETTING_INDEX_FILTER_MENU_TITLE: "Mail filter rules",
  SETTING_INDEX_REFER_MENU: "Share",
  SETTING_INDEX_REFER_MENU_TITLE: "Share yourself with other mailboxes, then other email can log into your account",
  SETTING_INDEX_SMTP_MENU: "SMTP proxy",
  SETTING_INDEX_SMTP_MENU_TITLE: "Use other mail servers to send outbound messages",
  SETTING_INDEX_ACCCANCEL_MENU: "Apply to Delete",
  // 个人资料
  SETTING_USER_NOTICE: "Tip: The modification request has been submitted, please wait for the review.",
  SETTING_USER_TITLE_1: "Basic Information",
  SETTING_USER_TITLE_2: "Contact Info",
  SETTING_USER_TITLE_3: "Contact address",
  SETTING_USER_BUTTON_HIDE: "Show more",
  SETTING_USER_BUTTON_SHOW: "Hide more",
  SETTING_USER_BUTTON_SHENHE: "Submit audit",
  SETTING_USER_NAME_RULE: "Please enter name",
  SETTING_USER_NAME_RULE_LEN: "Length 1 to 35 characters",
  SETTING_USER_ENGNAME: "English name",
  SETTING_USER_EENUMBER: "Job number",
  SETTING_USER_TELHOME: "Home Phone",
  SETTING_USER_HOMEPAGE: "Homepage",
  SETTING_USER_CONTRY: "Contry",
  SETTING_USER_STATE: "Province",
  SETTING_USER_CITY: "City",
  SETTING_USER_ZIP: "Zip code",
  SETTING_USER_ADDRESS: "Address",
  SETTING_USER_MESSAGE_1: "The modification application has been submitted, please wait for review.",
  SETTING_USER_MESSAGE_2: "No changes to the profile.",
  // 修改密码
  SETTING_PASSWORD_SECURITY_TITLE: "Set security",
  SETTING_PASSWORD_SECURITY_Q1: "Secret 1",
  SETTING_PASSWORD_SECURITY_Q2: "Secret 2",
  SETTING_PASSWORD_SECURITY_Q3: "Secret 3",
  SETTING_PASSWORD_SECURITY_QP: "please select secret question",
  SETTING_PASSWORD_SECURITY_QS: "Custom question",
  SETTING_PASSWORD_SECURITY_QA: "Answer",
  // 安全中心
  SETTING_TWOFACTOR_TITLE: "Two-factor authentication: to enhance mailbox security, you can request authentication before logging into your mailbox",
  SETTING_TWOFACTOR_ALERT: "Two-factor authentication can improve the security level of your account, and we strongly recommend that you bind two-factor authentication.",
  SETTING_TWOFACTOR_GOOGLE_ENABLE_TITLE: "Your account has been enabled for Google Authentication.",
  SETTING_TWOFACTOR_GOOGLE_DISABLE_TITLE: "Google Authentication is not enabled for your account. Please enable Google Authentication to enhance account security.",
  SETTING_TWOFACTOR_GOOGLE_ENABLE: "Enable Google Authentication",
  SETTING_TWOFACTOR_GOOGLE_DISABLE: "Disable Google Authentication",
  SETTING_TWOFACTOR_GOOGLE_CODE: "Google Authentication Code",
  SETTING_TWOFACTOR_GOOGLE_CODE_PLACE: "please enter code",
  SETTING_TWOFACTOR_STEP: "Step",
  SETTING_TWOFACTOR_STEP_NEXT: "Next",
  SETTING_TWOFACTOR_STEP_PRE: "Previous",
  SETTING_TWOFACTOR_STEP1: "1. Download App",
  SETTING_TWOFACTOR_STEP2: "2. Scan QR Code",
  SETTING_TWOFACTOR_STEP3: "3. Backup Key",
  SETTING_TWOFACTOR_STEP4: "4. Enable Google Authentication",
  SETTING_TWOFACTOR_STEP1_TITLE: "Download and install the Google Authentication app",
  // SETTING_TWOFACTOR_STEP1_METHOD1: "方法一：手机应用市场搜索“身份宝 ”并下载App，或",
  // SETTING_TWOFACTOR_STEP1_METHOD10: "扫码下载",
  // SETTING_TWOFACTOR_STEP1_METHOD2: "方法二：手机应用市场搜索“宁盾令牌 ”并下载App",
  // SETTING_TWOFACTOR_STEP1_METHOD3: "方法三：手机应用市场搜索“Google Authenticator ”并下载App，或",
  SETTING_TWOFACTOR_STEP1_METHOD1: "",
  SETTING_TWOFACTOR_STEP1_METHOD10: "",
  SETTING_TWOFACTOR_STEP1_METHOD2: "",
  SETTING_TWOFACTOR_STEP1_METHOD3: "",
  SETTING_TWOFACTOR_STEP1_FOOTER: "I have installed the app",
  SETTING_TWOFACTOR_STEP2_TITLE: "Scan this QR code in the Google Authentication app",
  SETTING_TWOFACTOR_STEP2_MID: "If you are unable to scan the QR code, please enter this code manually into the app.",
  SETTING_TWOFACTOR_STEP2_FOOTER: "I have scanned the QR code",
  SETTING_TWOFACTOR_STEP3_TITLE: "Please save this Key on paper. This Key will allow you to recover your Google Authentication in case of phone loss.",
  SETTING_TWOFACTOR_STEP3_MID: "Also clear your Google authentication by contacting the administrator.",
  SETTING_TWOFACTOR_STEP3_FOOTER: "I have already written down the 16-Digit Key",
  SETTING_TWOFACTOR_STEP4_TITLE: "Enable Google Authentication",
  SETTING_TWOFACTOR_PHONE_ENABLE_TITLE: "Your account has been enabled for SMS Authentication.",
  SETTING_TWOFACTOR_PHONE_DISABLE_TITLE: "SMS Authentication is not enabled for your account. Please enable SMS Authentication to enhance account security.",
  SETTING_TWOFACTOR_PHONE_ENABLE: "Enable SMS Authentication",
  SETTING_TWOFACTOR_PHONE_DISABLE: "Disable SMS Authentication",
  SETTING_TWOFACTOR_PHONE_CODE: "SMS Authentication Code",
  SETTING_TWOFACTOR_PHONE_SECOND: " seconds later",
  SETTING_TWOFACTOR_PHONE_RULE: "please enter your mobile phone number",
  SETTING_TWOFACTOR_PHONE_CODE_RULE: "please enter code",
  SETTING_TWOFACTOR_GOOGLE_CODE_RULE: "please enter code",
  SETTING_TWOFACTOR_GOOGLE_BOUND_S: "Google Authentication bound successfully!",
  SETTING_TWOFACTOR_GOOGLE_BOUND_F: "Google Authentication bound failed!",
  SETTING_TWOFACTOR_GOOGLE_RELEASE_S: "Google Authentication unbound successfully!",
  SETTING_TWOFACTOR_GOOGLE_RELEASE_F: "Google Authentication unbound failed!",
  SETTING_TWOFACTOR_PHONE_BOUND_S: "SMS Authentication bound successfully!",
  SETTING_TWOFACTOR_PHONE_BOUND_F: "SMS Authentication bound failed!",
  SETTING_TWOFACTOR_PHONE_RELEASE_S: "SMS Authentication unbound successfully!",
  SETTING_TWOFACTOR_PHONE_RELEASE_F: "SMS Authentication unbound failed!",
  // 参数设置
  SETTING_PARAM_CHARSET: "Convert Character Set",
  SETTING_PARAM_SAVE_WEBMAIL: "Save sent messages in Sent folder",
  SETTING_PARAM_SAVE_CLIENT: "Save to Sent when sent messages through SMTP",
  SETTING_PARAM_SAVE_CONTACT: "Automatically save recipients to contacts",
  SETTING_PARAM_AUTO_RECAIPT: "Automatically Reply",
  SETTING_PARAM_SAVE_DRAFT: "Automatically save draft",
  SETTING_PARAM_LOGIN_OVERTIME: "Session timeout",
  SETTING_PARAM_LOGIN_OVERTIME_M10: "10 minutes",
  SETTING_PARAM_LOGIN_OVERTIME_M15: "15 minutes",
  SETTING_PARAM_LOGIN_OVERTIME_M30: "30 minutes",
  SETTING_PARAM_LOGIN_OVERTIME_H1: "1 hour",
  SETTING_PARAM_LOGIN_OVERTIME_H2: "2 hours",
  SETTING_PARAM_LOGIN_OVERTIME_H8: "8 hours",
  SETTING_PARAM_MAIL_READ_TYPE: "Mail reading method",
  SETTING_PARAM_MAIL_READ_TYPE_H: "Read Hypertext Content (H)",
  SETTING_PARAM_MAIL_READ_TYPE_T: "Read plain text content (T)",
  //皮肤中心
  SETTING_SKIN_TITLE: "Main theme",
  // SETTING_SKIN_JINGDIANLAN: "经典蓝（默认）",
  // SETTING_SKIN_CHUNZHIHUA: "春之花",
  // SETTING_SKIN_YANYUJIANGNAN: "烟雨江南",
  // SETTING_SKIN_HETANGYUESE: "荷塘月色",
  // SETTING_SKIN_QINGXINLU: "清新绿",
  // SETTING_SKIN_HAISHUILAN: "海水蓝",
  // SETTING_SKIN_ZHONGGUOFENG: "中国风",
  SETTING_SKIN_JINGDIANLAN: "Classic Blue (default)",
  SETTING_SKIN_CHUNZHIHUA: "Flowers of Spring",
  SETTING_SKIN_YANYUJIANGNAN: "",
  SETTING_SKIN_HETANGYUESE: "Moonlight of Lotus Pond",
  SETTING_SKIN_QINGXINLU: "Fresh Green",
  SETTING_SKIN_HAISHUILAN: "Sea Blue",
  SETTING_SKIN_ZHONGGUOFENG: "Chinese Wind",
  SETTING_SKIN_TIANKONGLAN: "Sky Blue",
  SETTING_SKIN_CHENLU: "Morning Heron",
  SETTING_SKIN_CAODI: "Grassland",
  SETTING_SKIN_MUWEN: "Wood grain",
  SETTING_SKIN_TAOHUAHONG: "Peach Blossom Red",
  SETTING_SKIN_KEAIFEN: "Cute Powder",
  SETTING_SKIN_JIANLAN: "Simple Blue",
  SETTING_SKIN_JIANLU: "Simple Green",
  SETTING_SKIN_JIANQING: "Simple Cyan",
  SETTING_SKIN_MSG: "Set skin successfully!",
  // 签名
  SETTING_SIG_BUTTON_ADD: "New Signature",
  SETTING_SIG_BUTTON_DEFAULT: "Set default signature",
  SETTING_SIG_DEFAULT_SUBJECT: "New mail default",
  SETTING_SIG_REFW_DEFAULT_SUBJECT: "Re/Fw default",
  SETTING_SIG_DEFAULT_MAIL: "New mail default",
  SETTING_SIG_DEFAULT_REFW: "Re/Fw default",
  SETTING_SIG_SIG_DEFAULT_MAIL: "no default",
  SETTING_SIG_SUBJECT: "Title",
  SETTING_SIG_CONTENT: "Content",
  SETTING_SIG_ADDTITLE: "New Signature",
  SETTING_SIG_UPDATETITLE: "Edit Signature",
  SETTING_SIG_SUBJECT_RULE: "please enter title",
  SETTING_SIG_CONTENT_RULE: "please enter content",
  // 模板信
  SETTING_TEMPLATE_ADD: "New Template",
  SETTING_TEMPLATE_UPDATE: "Edit Template",
  SETTING_TEMPLATE_SUBJECT: "Title",
  SETTING_TEMPLATE_SUBJECT_RULE: "please enter title",
  SETTING_TEMPLATE_CONTENT_RULE: "please enter content",
  // 自动回复
  SETTING_RE_LOGIC: "Relationship",
  SETTING_RE_LOGIC_ALL: "all",
  SETTING_RE_LOGIC_ONE: "one",
  SETTING_RE_LOGICS: "Conditions",
  SETTING_RE_LOGIC_ALLMAIL: "all mails",
  SETTING_RE_LOGIC_HASATTACH: "has attachment",
  SETTING_RE_LOGIC_ATTACH: "attachment name",
  SETTING_RE_LOGIC_SENDER: "sender",
  SETTING_RE_LOGIC_CC: "cc",
  SETTING_RE_LOGIC_RECIPIENT: "recipient",
  SETTING_RE_LOGIC_SENDER_DEPART: "sender department",
  SETTING_RE_LOGIC_CC_DEPART: "cc department",
  SETTING_RE_LOGIC_RCPT_DEPART: "recipient department",
  SETTING_RE_LOGIC_CONTENT: "mail content",
  SETTING_RE_LOGIC_SIZEMB: "mail size(MB)",
  SETTING_RE_LOGIC_SIZEB: "mail size(Byte)",
  SETTING_RE_LOGIC_EXECTIME: "execute time",
  SETTING_RE_LOGIC_SIZECB: "mail body size(Byte)",
  SETTING_RE_SUBLOGIC_C: "contains",
  SETTING_RE_SUBLOGIC_NC: "not contain",
  SETTING_RE_SUBLOGIC_E: "equal to",
  SETTING_RE_SUBLOGIC_GE: "greater or equal to",
  SETTING_RE_SUBLOGIC_LE: "less than or equal to",
  SETTING_RE_SUBLOGIC_B: "belong",
  SETTING_RE_SUBLOGIC_NB: "not belong",
  SETTING_RE_SUBLOGIC_DATETO: "to",
  SETTING_RE_SUBLOGIC_AND: "and",
  SETTING_RE_SUBLOGIC_OR: "or",
  SETTING_RE_ADD_LOGICP: "Relationship",
  SETTING_RE_ADD_LOGICP_BUTTON: "New Parent",
  SETTING_RE_ADD_LOGICC: "Relationship",
  SETTING_RE_ADD_WEEK: "week",
  SETTING_RE_ADD_DAY: "day",
  SETTING_RE_ADD_CONTENT_RULE: "please enter content",
  SETTING_RE_ADD_SELECTDPT: "Click to select department",
  SETTING_RE_ADD_SELECTDPT_PLACE: "Click to select department",
  SETTING_RE_ADD_WEEK_START_PLACE: "start week",
  SETTING_RE_ADD_WEEK_END_PLACE: "end week",
  SETTING_RE_ADD_WEEK_TIMESTART_PLACE: "start time",
  SETTING_RE_ADD_WEEK_TIMEEND_PLACE: "end time",
  SETTING_RE_ADD_DAY_TIMESTART_PLACE: "start date time",
  SETTING_RE_ADD_DAY_TIMEEND_PLACE: "end date time",
  SETTING_RE_ADD_CONTENT: "reply content",
  SETTING_RE_ADD_RULE_1: "please enter reply content!",
  SETTING_RE_ADD_RULE_2: "please select action!",
  SETTING_RE_ADD_RULE_3: "please enter condition content!",
  SETTING_RE_ADD_RULE_4: "please enter condition content!",
  SETTING_RE_ADD_RULE_5: "start week cannot be greater than end week!",
  SETTING_RE_ADD_RULE_6: "start time cannot be greater than end time!",
  // 自动转发
  SETTING_FW_FORWARD: "Forwarded to",
  SETTING_FW_FORWARD_DESC: "please enter email",
  SETTING_FW_FORWARD_RULE: "please enter email!",
  SETTING_FW_ISFORWARD: "Forwarded option",
  SETTING_FW_ISFORWARD_DESC: "save messages in your folder",
  // 邮件过滤
  SETTING_FILTER_NAME: "Name",
  SETTING_FILTER_NAME_RULE: "please enter name",
  SETTING_FILTER_PRIORITY: "Priority",
  SETTING_FILTER_PRIORITY_RULE: "please enter priority",
  SETTING_FILTER_ACTION: "Action",
  SETTING_FILTER_ACTION1: "delete message",
  SETTING_FILTER_ACTION2: "quarantine message",
  SETTING_FILTER_ACTION3: "move message to folder",
  SETTING_FILTER_ACTION4: "copy message to folder",
  SETTING_FILTER_ACTION5: "forwarded",
  SETTING_FILTER_ACTION_FOLDER1: "Spam",
  SETTING_FILTER_ACTION_FOLDER2: "Trash",
  SETTING_FILTER_ACTION_FOLDER3: "Inbox",
  SETTING_FILTER_ACTION_FOLDER4: "Sent",
  SETTING_FILTER_RULE1: "please enter condition priority!",
  SETTING_FILTER_RULE2: "please enter action content!",
  SETTING_FILTER_RULE3: "please enter action priority!",
  // 白名单
  SETTING_WHITE_DESC: "Notice: Letters from whitelist will bypass the anti-spam system and reach the inbox directly. The whitelist can be an email address or a domain, for example: zhangsan@example.com or @example.com.",
  SETTING_WHITE_EMAIL_RULE1: "Please enter email",
  SETTING_WHITE_EMAIL_RULE2: "Please enter correct email",
  // 黑名单
  SETTING_BLACK_DESC: "Notice: System automatically rejectes blacklist emails. The blacklist can be an email address or a domain, for example: zhangsan@example.com or @example.com.",
  // 邮箱搬家
  SETTING_MOVE_DESC: "Notice: if you have a mailbox of \"zhangsan@example.com\", you can use this function to automatically receive all emails of \"zhangsan@example.com\" in current mailbox.",
  SETTING_MOVE_ADD: "Add",
  SETTING_MOVE_RECEIVE: "Receive",
  SETTING_MOVE_RECEIVE2: "Receive",
  SETTING_MOVE_PROTOCOL: "Protocol",
  SETTING_MOVE_TASK: "Information",
  SETTING_MOVE_STATUS: "Active Status",
  SETTING_MOVE_STATUS2: "Move status",
  SETTING_MOVE_UPDATED: "Last Receive Time",
  SETTING_MOVE_ADD_SERVER: "Server",
  SETTING_MOVE_ADD_SERVER_RULE: "please enter server",
  SETTING_MOVE_ADD_PROTOCOL: "Protocol",
  SETTING_MOVE_ADD_EMAIL: "Moved email",
  SETTING_MOVE_ADD_EMAIL_RULE: "please enter the moved email",
  SETTING_MOVE_ADD_PASSWORD: "Password",
  SETTING_MOVE_ADD_PASSWORD_RULE: "please enter password",
  SETTING_MOVE_ADD_PASSWORD_DESC: "Please enter the password corresponding to the above email address. Some email service providers only allow third-party clients to log in with the \"authorization code\", so you need to enter the \"authorization code\" provided by the service provider instead.",
  SETTING_MOVE_ADD_SSL_DESC: "SSL mode login, Please consult the server provider for setting requirements if this option is checked",
  SETTING_MOVE_ADD_FOLDER: "Migrate Forlder",
  SETTING_MOVE_ADD_FOLDER_DESC1: "All",
  SETTING_MOVE_ADD_FOLDER_DESC2: "Only Inbox",
  SETTING_MOVE_RECEIVE_SUBMIT: "Do you confirm to receive the mail?",
  SETTING_MOVE_RECEIVE_MSG: "Email received successfully, please be patient!",
  // 收件短信通知
  SETTING_SMS_MODE: "SMS Notification mode",
  SETTING_SMS_MODE1: "No notification for all incoming mails",
  SETTING_SMS_MODE2: "Notification for all incoming mails",
  SETTING_SMS_MODE3: "Notification for only in whitelist",
  SETTING_SMS_MODE3_TITLE: "SMS Notification Whitelist",
  SETTING_SMS_MODE3_DESC: "Notice: whitelist can be an email address or a domain, for example: zhangsan@example.com or @example.com.",
  // 邮箱意见反馈
  SETTING_FEEDBACK_DESC: "Thank you very much for your recognition and support of our service all the time. Your enthusiastic feedback is the source of our continuous improvement of service. I hope to take a few minutes of your time to give feedback to our service.",
  SETTING_FEEDBACK_NAME: "Your Name",
  SETTING_FEEDBACK_EMAIL: "Your Email",
  SETTING_FEEDBACK_PHONE: "Your Mobile Phone",
  SETTING_FEEDBACK_NOTE: "Feedback",
  SETTING_FEEDBACK_NOTE_RULE: "please enter feedback",
  SETTING_FEEDBACK_MSG: "Sent successfully",
  // 邮件召回记录
  // 关联共享邮箱
  SETTING_REFER_EMAIL: "Email",
  SETTING_REFER_IMPORT_LOADING: "Importing file...",
  SETTING_REFER_MODE: "Method",
  SETTING_REFER_MODE1: "Input or select Corporate",
  SETTING_REFER_MODE2: "Import Excel",
  SETTING_REFER_PERM1: "read-only",
  SETTING_REFER_PERM2: "read and write",
  SETTING_REFER_PERM3: "proxy send",
  SETTING_REFER_PERM4: "fully control",
  SETTING_REFERE_EMAIL_DESC1: "Support multiple mailboxes, please use semicolon (;) to Separated",
  SETTING_REFERE_EMAIL_DESC2: "please enter email",
  SETTING_REFERE_EMAIL_DESC3: "Clear",
  SETTING_REFERE_EMAIL_SELECT: "select email",
  SETTING_REFERE_EMAIL_NAME: "name or email",
  SETTING_REFERE_FILE: "select file",
  SETTING_REFERE_TEMPLATE: "View Excel Template",
  // SMTP外发代理
  SETTING_SMTP_SERVER: "SMTP Server",
  SETTING_SMTP_ACC: "Account",
  SETTING_SMTP_PASSWD: "Password",
  SETTING_SMTP_SSL: "SSL",
  SETTING_SMTP_AUTH: "Need Verify",
  SETTING_SMTP_AUTH_DESC: "Unless the other server is turned on password-free authentication, otherwise it must be checked",
  SETTING_SMTP_REMARK1: "It will be verified when submitting. It may need to wait for 3-10 seconds. Please re-verify the timeout.",
  SETTING_SMTP_REMARK2: "QQ mailbox login need to open the \"authorization code\", you can not log in directly using the password. For more information, visit this page for \"E-mail Authorization Code setting \".",
  SETTING_SMTP_REMARK3: "Just set the account will log in to the target server to perform a verification, if the verification fails, you can not set the data.",
  SETTING_SMTP_REMARK4: "When the mail is out of the station, if the setting of the relay server can not be verified or sent, it will be changed from the station to the station, and there will be an e-mail (once every 2 hours).",
  SETTING_SMTP_SERVER_RULE: "please enter your SMTP Server",
  SETTING_SMTP_ACC_RULE: "please enter your account",
  SETTING_SMTP_PASSWD_RULE: "please enter your password",
  // 申请注销用户
  SETTING_ACCCANCEL_ALERT: "Notice:The cancellation application has been submitted, please wait patiently for review",
  SETTING_ACCCANCEL_TITLE: "Apply to Delete",
  SETTING_ACCCANCEL_REMARK: "Reason",
  SETTING_ACCCANCEL_REMARK_RULE: "please enter reason",
  SETTING_ACCCANCEL_MSG: "Application has been submitted, please wait for review.",

  //layout/index  页面
  LAYOUT_INDEX_PERSONAL_SETTINGS:'Setting',
  LAYOUT_INDEX_LOGOUT:'Logout',
  LAYOUT_INDEX_SCHOLARS:'论客',
  LAYOUT_INDEX_HELP_CENTER:'Help',
  LAYOUT_INDEX_BACK_STAGE_MANAGEMENT:'Manage backstage',
  LAYOUT_INDEX_SELF_QUERY:'Self-Service',
  LAYOUT_INDEX_MOBILE:'移动端',
  LAYOUT_INDEX_INSTANT_COMMUNICATION:'即时沟通',
  // LAYOUT_INDEX_MOVE_IMMEDIATELY:'马上搬家',
  LAYOUT_INDEX_MOVE_IMMEDIATELY:'Move immediately',
  LAYOUT_INDEX_SWITCHING_MAILBOX:'Switch accounts',
  LAYOUT_INDEX_ASSOCIATED_SHARED_MAILBOX:'Associated accounts',
  LAYOUT_INDEX_RETURN_TO_MAILBOX:'Back to Myself',
  LAYOUT_INDEX_SETTING:'Setting',
  LAYOUT_INDEX_SKIN_PEELER:'Set Skin',
  LAYOUT_INDEX_MORE_SKIN:'More skins...',
  LAYOUT_INDEX_LOCK_SCREEN:'Lock Screen',
  LAYOUT_INDEX_SEARCH_OF_MAIL:'Search Messages',
  LAYOUT_INDEX_YOU_HAVE:'You have ',
  LAYOUT_INDEX_AUDITED_EMAIL:' emails to review, click to review now',
  LAYOUT_INDEX_MODIFY_PASSWORD:'Password is weak, please change it',
  LAYOUT_INDEX_MY_MAILBOX:'Mailbox',
  LAYOUT_INDEX_MY_SCHEDULE:'Calendar',
  LAYOUT_INDEX_PASSWORD_RULE:'Please enter your password!',
  LAYOUT_INDEX_PASSWORD_RULE_AGAIN:'Please enter your password again!',
  LAYOUT_INDEX_TWO_INCONSISTENT_PASSWORDS:'New password mismatch!',
  LAYOUT_INDEX_FILE_CENTER:'File',
  LAYOUT_INDEX_CONTACTS:'Contact',
  LAYOUT_INDEX_SKIN_SETUP_SUCCESSFUL:'Set skin successfully!',
  LAYOUT_INDEX_SUCCESSFUL_PASSWORD:'Change password successfully!',
  LAYOUT_INDEX_LOGOUT_CONFIRM:'Confirm logout?',
  LAYOUT_INDEX_LOCK_SCREEN_NOTICE1:'Your mailbox will be locked.',
  LAYOUT_INDEX_LOCK_SCREEN_NOTICE2:'Your mailbox will be kept online.',
  LAYOUT_INDEX_LOCK_SCREEN_NOTICE3:"Anyone can not operate for your mailbox but entering correct Password.",
  LAYOUT_INDEX_LOCK_SCREEN_NOTICE4:'Protect your privacy in mailbox effectively.',
  LAYOUT_INDEX_LOCK_SCREEN_TITLE:'Lock Screen Tips',
  LAYOUT_INDEX_LOCK_SCREEN_SURE:'Lock',
  LAYOUT_INDEX_SWITCH_SHARE_MAILBOX:'Switch accounts error!',


  // mailbox/mailboxTab 邮箱 框架页面
  MAILBOX_WRITE_LETTERS:"New",
  MAILBOX_ADD_FOLDERS:"New Folder",
  MAILBOX_REFRESH_MAILING_LIST:"Refresh",
  MAILBOX_NEW_FOLDER:"New Folder",
  MAILBOX_MAIL_AUDIT:"Review Email",
  MAILBOX_FOLDER_NAME:"Name",
  MAILBOX_CLOSE_ALL_TABS:"Close all",
  MAILBOX_INBOX:"Inbox",
  MAILBOX_FOLDER_NAME_RULES:"please enter name!",
  MAILBOX_SHARE_POWER: "There is no permission to do this for the shared mailbox you are logged into.",
  MAILBOX_NO_SUBJECT:"No subject",
  MAILBOX_WRITING:"You are composing now. Are you going to leave?",
  MAILBOX_CONFIRM_DELETION1:"Confirm deleting ",
  MAILBOX_CONFIRM_DELETION2:"  folders? The message will be deleted after execution. This operation is not recoverable. Do you want to execute it?",


  // mailbox/components/home 首页
  MAILBOX_COM_HOME_HELLO:'Hello,',
  MAILBOX_COM_HOME_UNREAD:' Unreaded',
  MAILBOX_COM_HOME_NO_UNREAD:'No unread mail',
  MAILBOX_COM_HOME_MAILBOX_CAPACITY:'MailBox Using',
  MAILBOX_COM_HOME_RECENT_LOGIN:'Last login',
  MAILBOX_COM_HOME_DETAILS:'Detail',
  MAILBOX_COM_HOME_WELCOME_USER:"Welcome to Webmail",
  MAILBOX_COM_HOME_MAILBOX_FUNCTION:"What's",
  MAILBOX_COM_HOME_MAILBOX_FUNCTION_QUERY:"Support mailbox used record query, unread message recall, remote login remind",
  MAILBOX_COM_HOME_MAILBOX_FUNCTION_FILE:"Support major browser continuous transmission (include Chrome, Firefox)",
  MAILBOX_COM_HOME_MAILBOX_SCHEDULE:"Schedule management",
  MAILBOX_COM_HOME_MAILBOX_SCHEDULE_DESC:"New featured calendar, advanced version support meeting invitations and calendar sharing",
  MAILBOX_COM_HOME_CONTACTS:"Contact",
  MAILBOX_COM_HOME_CONTACTS_DESC:"Search and synchronize address book in Outlook and Foxmail",
  MAILBOX_COM_HOME_SETTINGS_DESC:"Profile, template letter, signature and other Settings",

  //mailbox/components/innerbox 邮件列表页面
  MAILBOX_COM_INNERBOX_SORT: "Sort",
  MAILBOX_COM_INNERBOX_SEE: "View",
  MAILBOX_COM_INNERBOX_MOVE_TO: "Move",
  MAILBOX_COM_INNERBOX_MARKED_AS: "Mark",
  MAILBOX_COM_INNERBOX_MORE: "More",
  MAILBOX_COM_INNERBOX_REFRESH: "Refresh",
  MAILBOX_COM_INNERBOX_MORE_SEARCH: "More search",
  MAILBOX_COM_INNERBOX_HIDE: "Hide",
  MAILBOX_COM_INNERBOX_SEAL: "", // 邮件列表界面未读 封
  MAILBOX_COM_INNERBOX_UNREAD: "Unread",
  MAILBOX_COM_INNERBOX_ALL_READ: ", Mark All As Read",
  MAILBOX_COM_INNERBOX_SEAL_SELECTED: " email(s) selected",  // 邮件列表界面已选择 封
  // MAILBOX_COM_INNERBOX_HAVE_CHOSEN: "已选择",
  MAILBOX_COM_INNERBOX_HAVE_CHOSEN: "", // 已选择
  MAILBOX_COM_INNERBOX_ENCLOSURE: "Attach",
  MAILBOX_COM_INNERBOX_URGENT_MAIL: "Urgent Mail",
  MAILBOX_COM_INNERBOX_SET_FLAG: "Set Flag",
  MAILBOX_COM_INNERBOX_ALL: "All",
  MAILBOX_COM_INNERBOX_CURRENT_PAGE: "Current page",
  MAILBOX_COM_INNERBOX_ALREADY_READ: "Read",
  MAILBOX_COM_INNERBOX_REVERSE_ELECTION: "Inverse",
  MAILBOX_COM_INNERBOX_NO_ELECTION: "None",
  MAILBOX_COM_INNERBOX_NEW_TO_OLD: "Time Desc",
  MAILBOX_COM_INNERBOX_OLD_TO_NEW: "Time Asc",
  MAILBOX_COM_INNERBOX_UPGRADE_BY_SENDER: "Fom Desc",
  MAILBOX_COM_INNERBOX_DESCEND_BY_SENDER: "Fom Asc",
  MAILBOX_COM_INNERBOX_DESCEND_BY_SUBJECT: "Title Desc",
  MAILBOX_COM_INNERBOX_UPGRADE_BY_SUBJECT: "Title Asc",
  MAILBOX_COM_INNERBOX_SMALL_TO_BIG: "Size Desc",
  MAILBOX_COM_INNERBOX_BIG_TO_SMALL: "Size Asc",
  MAILBOX_COM_INNERBOX_ALL_MAIL: "All Mail",
  MAILBOX_COM_INNERBOX_UNREAD_MAIL: "Unread",
  MAILBOX_COM_INNERBOX_READ_MAIL: "Read",
  MAILBOX_COM_INNERBOX_MARKED_MAIL: "Flagged",
  MAILBOX_COM_INNERBOX_UNMARKED_MAIL: "Unflagged",
  MAILBOX_COM_INNERBOX_OTHER_MARKERS: "Other Flag",
  MAILBOX_COM_INNERBOX_OTHER_FLAG: "Other Flag",
  MAILBOX_COM_INNERBOX_RED_FLAG: "Flagged",
  MAILBOX_COM_INNERBOX_GREEN_FLAG: "Green flag",
  MAILBOX_COM_INNERBOX_ORANGE_FLAG: "Orange flag",
  MAILBOX_COM_INNERBOX_BLUE_FLAG: "Blue flag",
  MAILBOX_COM_INNERBOX_PINK_FLAG: "Pink flag",
  MAILBOX_COM_INNERBOX_CYAN_FLAG: "Cyan flag",
  MAILBOX_COM_INNERBOX_YELLOW_FLAG: "Yellow flag",
  MAILBOX_COM_INNERBOX_PURPLE_FLAG: "Purple flag",
  MAILBOX_COM_INNERBOX_GREY_FLAG: "Grey flag",
  MAILBOX_COM_INNERBOX_RECOVERED: "Replied",
  MAILBOX_COM_INNERBOX_FORWARDED: "Forwarded",
  MAILBOX_COM_INNERBOX_REGULAR_MAIL: "Regular Mail",
  MAILBOX_COM_INNERBOX_CANCEL_FLAG: "Cancel Flag",
  MAILBOX_COM_INNERBOX_RECOVER: "Reply",
  MAILBOX_COM_INNERBOX_RECOVER_ALL: "Reply All",
  MAILBOX_COM_INNERBOX_FORWARD: "Forward",
  MAILBOX_COM_INNERBOX_ANNEX_FORWARDING: "Forward with Attach",
  MAILBOX_COM_INNERBOX_REJECTED_MAIL: "Reject Mail",
  MAILBOX_COM_INNERBOX_SEND_AGAIN: "Send Again",
  MAILBOX_COM_INNERBOX_PACKAGE_DOWNLOAD: "Download",
  MAILBOX_COM_INNERBOX_DELETE_THOROUGHLY: "Real Delete",
  MAILBOX_COM_INNERBOX_EMPTY_FOLDER: "Empty Folder",
  MAILBOX_COM_INNERBOX_MAIL_MARKUP_SUCCESSFUL: "Flagged successfully!",
  MAILBOX_COM_INNERBOX_MAIL_MARKUP_FAILED: "Flagged failed!",
  MAILBOX_COM_INNERBOX_MAIL_MOVE_SUCCESSFUL: "Move successfully!",
  MAILBOX_COM_INNERBOX_MAIL_MOVE_FAILED: "Move failed!",
  MAILBOX_COM_INNERBOX_DELETE_MAIL: "Delete this message. ",
  MAILBOX_COM_INNERBOX_CONTINUE: "Do you want to continue?",
  MAILBOX_COM_INNERBOX_ONLY_ONE: "You can only select one email to proceed ",
  MAILBOX_COM_INNERBOX_REJECT_MAIL_1: "Add to blacklist will not receive any messages sent.",
  MAILBOX_COM_INNERBOX_REJECT_MAIL_2: "Are you sure to reject this mail ?",
  MAILBOX_COM_INNERBOX_REJECT_MAIL_3: "add to blacklist and delete mail",
  MAILBOX_COM_INNERBOX_DELETE_DESC: "Are you sure to delete this mail forever?",
  MAILBOX_COM_INNERBOX_RECOVERED_AND_FORWARDED: "Has been replied and forwarded.",
  MAILBOX_COM_INNERBOX_TODAY: "Today ",
  MAILBOX_COM_INNERBOX_YESTODAY: "Yestoday ",
  MAILBOX_COM_INNERBOX_BEFOREYESTODAY: "Before Yestoday ",
  MAILBOX_COM_INNERBOX_EARLIER: "Earlier ",
  // MAILBOX_COM_INNERBOX_AFTERNOON: " Afternoon ",
  // MAILBOX_COM_INNERBOX_MORNING: " Morning ",
  MAILBOX_COM_INNERBOX_AFTERNOON: " ",
  MAILBOX_COM_INNERBOX_MORNING: " ",

  // mailbox/components/read 读邮件页面
  MAILBOX_COM_READ_RECALLED: "recalled",
  MAILBOX_COM_READ_PRINT: "Print Message",
  MAILBOX_COM_READ_SET_FLAG: "Set Flag",
  MAILBOX_COM_READ_DELETE_FLAG: "Cancel Flag",
  MAILBOX_COM_READ_CHECK_EXCHANGES: "Related Mail",
  MAILBOX_COM_READ_NEW_WINDOW: "Open in New Win",
  MAILBOX_COM_READ_CONFERENCE: "New Meeting",
  MAILBOX_COM_READ_SEND_TO: " To ",
  MAILBOX_COM_READ_CC: "Cc",
  MAILBOX_COM_READ_ATTACH: "Attachments",
  MAILBOX_COM_READ_COUNT: " Item", // 个
  MAILBOX_COM_READ_AND_SO: "...etc.",
  MAILBOX_COM_READ_SEE_ALL_ATTACH: "More",
  MAILBOX_COM_READ_ENCRYPTED_DESC: "Email has been decrypted, following is decrypted message content:",
  MAILBOX_COM_READ_IS_NOTIFY_DESC: "Are you sure to send out read receipt? Send read receipt automatically.",
  MAILBOX_COM_READ_IS_BURN_DESC: "This is a self-destruct message!",
  MAILBOX_COM_READ_IS_CALENDAR_DESC: "This is a calendar sharing reminder email!",
  MAILBOX_COM_READ_IS_CALENDAR_EVENT_DESC: "This is a calendar event reminder email!",
  MAILBOX_COM_READ_SENT: "Send",
  MAILBOX_COM_READ_PASS: "You have accepted the invitation!",
  MAILBOX_COM_READ_REJECT: "You have declined the invitation!",
  MAILBOX_COM_READ_WAIT: "You have not processed the invitation yet!",
  MAILBOX_COM_READ_HIDE: "Hide",
  MAILBOX_COM_READ_IS_RECIPT: "Do you accept the invitation?",
  MAILBOX_COM_READ_IS_PASS: "accept",
  MAILBOX_COM_READ_IS_WAIT: "wait",
  MAILBOX_COM_READ_IS_REJECT: "reject",
  MAILBOX_COM_READ_IS_DELETE: "This event has been removed from your schedule!",
  MAILBOX_COM_READ_VIEW_DETAILS: "detail",
  MAILBOX_COM_READ_HIDE_DETAILS: "hide detail",
  MAILBOX_COM_READ_REFRESH: "fresh",
  MAILBOX_COM_READ_IS_SENDER_1: "To the recipient of ",
  MAILBOX_COM_READ_IS_SENDER_2: "senders, among them ",
  MAILBOX_COM_READ_IS_SENDER_3: "is already undelivered, ",
  MAILBOX_COM_READ_IS_SENDER_4: "is under review, ",
  MAILBOX_COM_READ_IS_SENDER_5: "is in isolation, ",
  MAILBOX_COM_READ_IS_SENDER_6: "is delivered, ",
  MAILBOX_COM_READ_IS_SENDER_7: "is already read, ",
  MAILBOX_COM_READ_IS_SENDER_8: "delivery failed",
  MAILBOX_COM_READ_PASSWORD_ERROR: "Wrong password, please re-enter",
  MAILBOX_COM_READ_THIS: "This message from ",
  MAILBOX_COM_READ_SECRET_MAIL: "is password protected.",
  MAILBOX_COM_READ_VIEW_DESC: "You must input the password to read the original content.",
  MAILBOX_COM_READ_FAST_AN: "Reply to all",
  MAILBOX_COM_READ_FULL_AN: "Switch to full mode",
  MAILBOX_COM_READ_SENDING: "Mailing...",
  MAILBOX_COM_READ_SEND_SUC: "Send mail successfully",
  MAILBOX_COM_READ_SEND_FAIL: "Send mail Failed",
  MAILBOX_COM_READ_SEND_AGAIN: "Reply to another message",
  MAILBOX_COM_READ_NOT_FOND: "Not found! Have you moved to another folder?",
  MAILBOX_COM_READ_MAIL_DOWNLOAD: "Download",
  MAILBOX_COM_READ_LETTER_HEAD: "View Header",
  MAILBOX_COM_READ_ORIGINAL_TEXT: "View Source",
  MAILBOX_COM_READ_INPUT_CONTENT: "please enter email content!",
  MAILBOX_COM_READ_PRINT_TITLE: "U-Mail Business Mailbox",
  MAILBOX_COM_READ_PRINT_TITLE_PAGE: "U-Mail Business Mailbox - Print Message",
  MAILBOX_COM_READ_NEW_W: "New Win",
  MAILBOX_COM_READ_NOTICE_SEND_SUC: "Send receipt success!",
  MAILBOX_COM_READ_NOTICE_SEND_FAIL: "Send receipt failed!",
  MAILBOX_COM_READ_PART_SEND_FAIL: "Partly send failed!",
  MAILBOX_COM_READ_MAIL_REJECT_SUC: "Reject mail success!",
  MAILBOX_COM_READ_MAIL_REJECT_FAIL: "Reject mail failed!",
  MAILBOX_COM_READ_DELETE_CONTINUE: "Delete this message, do you want to continue?",
  MAILBOX_COM_READ_DELETE_THROU_CONTINUE: "Delete this message completely, do you want to continue?",
  MAILBOX_COM_READ_SYSTEM_NOTICE: "System Information",


  //mailbox/components/review 邮件审核页面
  // MAILBOX_COM_REVIEW_PASS: "审核通过",
  // MAILBOX_COM_REVIEW_REJECT: "拒绝通过",
  MAILBOX_COM_REVIEW_PASS: "passed",
  MAILBOX_COM_REVIEW_REJECT: "rejected",
  MAILBOX_COM_REVIEW_WAIT_LIST: "Review list",
  MAILBOX_COM_REVIEW_PASS_LIST: "Passed list",
  MAILBOX_COM_REVIEW_REJECT_LIST: "Rejected List",
  MAILBOX_COM_REVIEW_DATE: "date",
  MAILBOX_COM_REVIEW_OTHER: "other",
  MAILBOX_COM_REVIEW_PASS_ACTION: "pass",
  MAILBOX_COM_REVIEW_REJECT_ACTION: "reject",
  MAILBOX_COM_REVIEW_VIEW_MAIL: "View mail",
  MAILBOX_COM_REVIEW_REJECT_MAIL: "reject to review",
  MAILBOX_COM_REVIEW_REJECT_REASON: "Rejected reason:",
  MAILBOX_COM_REVIEW_INPUT_REJECT_REASON: "Please enter rejected reason",
  MAILBOX_COM_REVIEW_TITLE_NAME: "Review Mail list",
  MAILBOX_COM_REVIEW_IS_PASS: "Approve the selected message?",

  // mailbox/components/compose 写信页面
  MAILBOX_COM_COMPOSE_SEND_SCHEDULE: "Mail Scheduler",
  MAILBOX_COM_COMPOSE_SAVE_DRAFTS: "Save",
  MAILBOX_COM_COMPOSE_PREV: "Previous",
  MAILBOX_COM_COMPOSE_NEXT: "Next",
  // MAILBOX_COM_COMPOSE_ORDER: "第",
  // MAILBOX_COM_COMPOSE_PAGE: "页",
  MAILBOX_COM_COMPOSE_ORDER: "",
  MAILBOX_COM_COMPOSE_PAGE: "",
  MAILBOX_COM_COMPOSE_LETTER: "Stationery",
  MAILBOX_COM_COMPOSE_LOADING_MORE_TEMPLATE: "loading more",
  MAILBOX_COM_COMPOSE_SET_TEMPLATE: "Add Template Letter",
  MAILBOX_COM_COMPOSE_SENDER: "From:",
  MAILBOX_COM_COMPOSE_RECIVER: "To:",
  MAILBOX_COM_COMPOSE_CCER: "Cc:",
  MAILBOX_COM_COMPOSE_BCC: "Bcc:",
  MAILBOX_COM_COMPOSE_SUBJECT: "Subject:",
  MAILBOX_COM_COMPOSE_REPLYTO: "Reply-to:",
  MAILBOX_COM_COMPOSE_ATTACH: "Attachment:",
  MAILBOX_COM_COMPOSE_CANCEL_CC: "Cancel Cc",
  MAILBOX_COM_COMPOSE_CC: "Cc",
  MAILBOX_COM_COMPOSE_CANCEL_BCC: "Cancel Bcc",
  MAILBOX_COM_COMPOSE_SHOW_BCC: "Bcc",
  MAILBOX_COM_COMPOSE_CANCEL_PART: "Cancel Bulk Single",
  MAILBOX_COM_COMPOSE_PART: "Bulk Single",
  MAILBOX_COM_COMPOSE_REPLY_TO: "Reply-to",
  MAILBOX_COM_COMPOSE_CANCEL_REPLY_TO: "Cancel Reply-to",
  MAILBOX_COM_COMPOSE_INPUT_EMAIL: "please enter email",
  MAILBOX_COM_COMPOSE_COUNT: " attachments, ",
  MAILBOX_COM_COMPOSE_TOTAL_COUNT: "size:",
  // MAILBOX_COM_COMPOSE_TOTAL_COUNT: "共",
  MAILBOX_COM_COMPOSE_DEL_ALL_ATTACH: "delete all",
  MAILBOX_COM_COMPOSE_HIDE_ATTACH: "hide",
  MAILBOX_COM_COMPOSE_SHOW_ATTACH: "expand",
  MAILBOX_COM_COMPOSE_NO_SECRET: "none encryption",
  MAILBOX_COM_COMPOSE_ADD_ATTACH: "Attach a file",
  MAILBOX_COM_COMPOSE_FROM_FILE: "From File center",
  MAILBOX_COM_COMPOSE_FROM_LOCAL: "Attach file",
  MAILBOX_COM_COMPOSE_NO_SIGN: "Cancel Signature",
  MAILBOX_COM_COMPOSE_EDIT_SIGN: "Edit Signature",
  MAILBOX_COM_COMPOSE_ALL_TEXT: "Plain Text",
  MAILBOX_COM_COMPOSE_HTML_TEXT: "Html",
  MAILBOX_COM_COMPOSE_SAVE_SENDBOX: "Save to Sent",
  MAILBOX_COM_COMPOSE_SET_PRIORITY: "Urgent",
  MAILBOX_COM_COMPOSE_CONFIRM_READ: "Need receipt",
  MAILBOX_COM_COMPOSE_IS_PASSWORD: "Mail Encryption",
  MAILBOX_COM_COMPOSE_IS_BURN: "Auto Delete Mail",
  MAILBOX_COM_COMPOSE_IS_BURN_DESC: "Over views or time limit, the message will self-destruct.",
  MAILBOX_COM_COMPOSE_IS_BURN_DESC1: "Limited Views:",
  MAILBOX_COM_COMPOSE_IS_BURN_DESC2: "(Settings can be unified to each recipient 1 to 99 times, after reading the letter beyond reads links will automatically lapse)",
  MAILBOX_COM_COMPOSE_IS_BURN_DESC3: "Mail destruction time:",
  MAILBOX_COM_COMPOSE_IS_BURN_DESC4: "(Mail is destroyed automatically at 0:00 on the set date)",
  MAILBOX_COM_COMPOSE_IS_PASSWORD_DESC: "This message should be encrypted with a password",
  MAILBOX_COM_COMPOSE_SET_PASSWORD: "Set Password:",
  MAILBOX_COM_COMPOSE_SET_PASSWORD_RULE: "(Please input 6 case sensitive characters, can not set space heading or tailing.)",
  MAILBOX_COM_COMPOSE_SET_SCHEDULE: "select datetime",
  MAILBOX_COM_COMPOSE_SET_SCHEDULE_DESC1: "This mail will be delivered to the recipient's mailbox ",
  MAILBOX_COM_COMPOSE_SET_SCHEDULE_DESC2: " ",
  MAILBOX_COM_COMPOSE_SENDER_TIME1: "Schedule will be delivered ",
  MAILBOX_COM_COMPOSE_SENDER_TIME2: " to send, and will save to Draft box",
  MAILBOX_COM_COMPOSE_ALREADY_SEND: "Send mail successfully",
  MAILBOX_COM_COMPOSE_HIDE_STATUS: "[hide send status]",
  MAILBOX_COM_COMPOSE_SHOW_STATUS: "[show send status]",
  MAILBOX_COM_COMPOSE_REFRESH: "[refresh]",
  MAILBOX_COM_COMPOSE_RECALL: "[recall]",
  MAILBOX_COM_COMPOSE_CONTINUE_EDIT: "[continue to edit]",
  MAILBOX_COM_COMPOSE_IS_PASSWORD_AND_PASSWORD: "The sent message is encrypted, the password is:",
  MAILBOX_COM_COMPOSE_PASSWORD_DESC: "The password is required to read this message, you should notify the recipients in some other way. ",
  MAILBOX_COM_COMPOSE_SEND_STATUS: "Send status",
  MAILBOX_COM_COMPOSE_SAVE_AUTO: "Auto Save",
  MAILBOX_COM_COMPOSE_SAVE_AUTO_DESC: "To save your contacts automatically, you can set",
  MAILBOX_COM_COMPOSE_RETURN_TO_MAILBOX: "return",
  MAILBOX_COM_COMPOSE_CONTINUE_WRITE: "continue",
  MAILBOX_COM_COMPOSE_ADD_ADDRESS: "Add sender",
  MAILBOX_COM_COMPOSE_SOAB_NAME: "domain:",
  MAILBOX_COM_COMPOSE_MAIL_ADDRESS: "Email",
  MAILBOX_COM_COMPOSE_DEPART_MAIL: "Department email",
  MAILBOX_COM_COMPOSE_FILENAME: "name",
  MAILBOX_COM_COMPOSE_FILESIZE: "size",
  MAILBOX_COM_COMPOSE_UPLOAD_ATTACH: "Updating files",
  MAILBOX_COM_COMPOSE_EDIT_EMAIL: "Edit", //修改邮箱
  MAILBOX_COM_COMPOSE_INPUT_MAIL_ADDRESS: "please enter email",
  MAILBOX_COM_COMPOSE_INPUT_MAIL_ADDRESS_RIGHT: "please enter correct email",
  MAILBOX_COM_COMPOSE_RECALL_FAIL: "Mail recall fails!",
  MAILBOX_COM_COMPOSE_CANCEL_ALL_ATTACH: "Cancel all added attachments?",
  MAILBOX_COM_COMPOSE_CANCEL_REPLY_TO_ADDRESS: "Cancel and clear Reply-to?",
  MAILBOX_COM_COMPOSE_ALL_TEMPLATE_NOTICE: "All template messages have been loaded!",
  MAILBOX_COM_COMPOSE_CHANGE_TEMPLATE_NOTICE: "After replace with mail template, the original content will be remove, remove or save ?",
  MAILBOX_COM_COMPOSE_CHANGE_TEMPLATE_SAVE: "remove and save",
  MAILBOX_COM_COMPOSE_CHANGE_TEMPLATE: "remove",
  MAILBOX_COM_COMPOSE_CHANGE_PAPER_NOTICE: "Use stationery to switch to Html editing!",
  MAILBOX_COM_COMPOSE_HTML_TO_TEXT: "The current text formatting will be lost if switch to the text editor mode. Are you sure?",
  MAILBOX_COM_COMPOSE_DELETE_ALL_CC: "Are you sure remove all cc address ?",
  MAILBOX_COM_COMPOSE_DELETE_ALL_bCC: "Are you sure remove all bcc address ?",
  MAILBOX_COM_COMPOSE_WRITE: "New",
  MAILBOX_COM_COMPOSE_SURE_RECALL: "Are you sure to recall this message? Recall this message and the system will send recall summary to you.",
  MAILBOX_COM_COMPOSE_ALERT_INPUT_RECIVER: "Empty recipient!",
  MAILBOX_COM_COMPOSE_ALERT_INPUT_SUBJECT: "Empty subject!",
  MAILBOX_COM_COMPOSE_ALERT_INPUT_CONTENT: "Empty mail content!",
  MAILBOX_COM_COMPOSE_ALERT_PASSWORD: "Incorrect password format! Please fill in again!",
  MAILBOX_COM_COMPOSE_ALERT_REPLY_TO: "The format of Reply-to is not correct! Please fill in again! (reply to sender if left blank)",
  MAILBOX_COM_COMPOSE_SEND_SUCCESS: "Send mail successfully!",
  MAILBOX_COM_COMPOSE_SAVE_SUCCESS: "Saved draft successfully!",
  MAILBOX_COM_COMPOSE_MAIL_LIST: "Mail list",
  MAILBOX_COM_COMPOSE_IMG_TYPE: "Uploaded images must be JPG/GIF/PNG/BMP!",
  MAILBOX_COM_COMPOSE_IMG_SIZE: "Uploaded image size cannot exceed 10MB!",
  MAILBOX_COM_COMPOSE_NO_GROUP_NAME: "Ungrouped contacts",


  // calendar/index  日程框架 页面
  CALENDAR_INDEX_CAL_MANAGER: "Calendar Settings",

  //calendar/page/set 日程设置 页面
  CALENDAR_PAGE_SET_MY_LIST: "My Lists",
  CALENDAR_PAGE_SET_NEW_SCHEDULE: "Add Calendar",
  CALENDAR_PAGE_SET_SCHEDULE: "Calendar",
  CALENDAR_PAGE_SET_SET_AND_SHARE: "Edit",
  CALENDAR_PAGE_SET_REMOVE: "Remove",
  CALENDAR_PAGE_SET_HIDE_DESC: "Hide shared calendar will not display this calendar on your schedule, but the hidden calendar is still broadcast content synchronization",
  CALENDAR_PAGE_SET_SHARE_TO_MYSCHEDULE: "Received Calendar",
  CALENDAR_PAGE_SET_SHARER: "Share User",
  CALENDAR_PAGE_SET_SHOW: "Show",
  CALENDAR_PAGE_SET_SCHEDULE_NAME: "Name:",
  CALENDAR_PAGE_SET_SHARE_TO: "Share To:",
  CALENDAR_PAGE_SET_CHOOSE_MAILBOX: "please select email",
  CALENDAR_PAGE_SET_CHOOSE_PERMISSION: "please select permission",
  CALENDAR_PAGE_SET_PERMISSION_READ: "only-read", // 查看权限（只读）
  CALENDAR_PAGE_SET_PERMISSION_EDIT: "edit", // 编辑权限
  CALENDAR_PAGE_SET_INPUT_VISIT: "enter invitee",
  CALENDAR_PAGE_SET_CREATE_SCHEDULE: "Create Calendar",
  CALENDAR_PAGE_SET_EDIT_SCHEDULE: "Edit Calendar",
  CALENDAR_PAGE_SET_QUIT_EDIT: "Cancel",
  CALENDAR_PAGE_SET_SURE_EDIT: "Submit",
  CALENDAR_PAGE_SET_SCHEDULE_NAME_RULES1: "please enter calendar name",
  CALENDAR_PAGE_SET_SCHEDULE_NAME_RULES2: "Length 1 to 20 characters",
  CALENDAR_PAGE_SET_SURE_DELETE1: "Confirm to delete ",
  CALENDAR_PAGE_SET_SURE_DELETE2: " calendar?",
  CALENDAR_PAGE_SET_SURE_DELETE3: "Other person's calendar you shared will delete forever when you delete it.",
  CALENDAR_PAGE_SET_CREATE_SUC: "Create successfully!", //创建成功！
  CALENDAR_PAGE_SET_CREATE_FAIL: "Create failed!",
  CALENDAR_PAGE_SET_NOT_SYS_NOTICE: "Cannot add a mailbox that is not in the system! Please re-enter!",
  CALENDAR_PAGE_SET_MAIL_TYPE: "E-mail format is incorrect!",

  // calendar/page/calendar 日程事件 页面
  CALENDAR_PAGE_CAL_NEW_EVENT: "New event",
  CALENDAR_PAGE_CAL_TOMATO_RED: "Tomato", // 番茄红
  CALENDAR_PAGE_CAL_RED_CRANE_COLOR: "Flamingo", // 红鹤色
  CALENDAR_PAGE_CAL_TANGERINE: "Tangerine", // 橘红
  CALENDAR_PAGE_CAL_BANANA_YELLOW: "Banana",// 香蕉黄
  CALENDAR_PAGE_CAL_SALVIA_GREEN: "Sage",// 鼠尾草绿
  CALENDAR_PAGE_CAL_BASIL_GREEN: "Basil",// 罗勒绿
  CALENDAR_PAGE_CAL_PEACOCK_BLUE: "Peaccock", // 孔雀蓝
  CALENDAR_PAGE_CAL_BLUEBERRY_COLOR: "Blueberry",// 蓝莓色
  CALENDAR_PAGE_CAL_LAVENDER: "Lavender",// 薰衣草色
  CALENDAR_PAGE_CAL_GRAPE_PURPLE: "Grape", // 葡萄紫
  CALENDAR_PAGE_CAL_GRAPHITE_BLACK: "Graphite", // 石墨黑
  CALENDAR_PAGE_CAL_TIME: "Start or End Time",
  CALENDAR_PAGE_CAL_INPUT_START_TIME: "select date",
  CALENDAR_PAGE_CAL_CHOOSE_TIME: "select time",
  CALENDAR_PAGE_CAL_INPUT_END_TIME: "select date",
  CALENDAR_PAGE_CAL_DAY_EVENT: "All day",
  CALENDAR_PAGE_CAL_REPEAT_EVENT: "Recurring",
  CALENDAR_PAGE_CAL_IS_REPEAT: "Whether to repeat",
  CALENDAR_PAGE_CAL_REPEAT_COUNT: "epeat frequency: repeat every",
  CALENDAR_PAGE_CAL_CHOOSE_REPEAT_EVENT: "Select repeat event",
  CALENDAR_PAGE_CAL_WEEK: "Week",
  CALENDAR_PAGE_CAL_MONTH: "Month",
  CALENDAR_PAGE_CAL_REPEAT: "", // 重复
  CALENDAR_PAGE_CAL_CHOOSE_REPEAT_TYPE: "please select repeat type",
  CALENDAR_PAGE_CAL_REPEAT_TO: "Repeat until",
  CALENDAR_PAGE_CAL_REPEAT_FOREVER: "Repeat forever",
  CALENDAR_PAGE_CAL_CHOOSE_REPEAT_ENDTIME: "select date",
  CALENDAR_PAGE_CAL_REPEAT_DESC: "Repeat summary: ",
  CALENDAR_PAGE_CAL_EVERY: "Every",
  CALENDAR_PAGE_CAL_REPEAT_DAY: "day(s) repeat",
  CALENDAR_PAGE_CAL_REPEAT_WEEK: "week(s) repeat",
  CALENDAR_PAGE_CAL_REPEAT_MONTH: " month on ",
  CALENDAR_PAGE_CAL_REPEAT_YEAR: " year on ",
  CALENDAR_PAGE_CAL_START_DAY: " start",
  CALENDAR_PAGE_CAL_NO_REPEAT: "Not repeat",
  CALENDAR_PAGE_CAL_PLACE: "Where",
  CALENDAR_PAGE_CAL_REMARK: "Description",
  CALENDAR_PAGE_CAL_REMIND: "Reminder",
  CALENDAR_PAGE_CAL_USER: "Organizer",
  CALENDAR_PAGE_CAL_VISITER: "Invitee",
  CALENDAR_PAGE_CAL_IS_REMIND: "Whether to remind (email)",
  CALENDAR_PAGE_CAL_REMIND_BEFORE: "Before",
  CALENDAR_PAGE_CAL_VISIT: "Invitee",
  CALENDAR_PAGE_CAL_CANCEL_VISIT: "Cancel",
  CALENDAR_PAGE_CAL_CREATE: "Save",
  CALENDAR_PAGE_CAL_IS_PASS: "Do you want to join this meeting?",
  CALENDAR_PAGE_CAL_PASS: "Accept",
  CALENDAR_PAGE_CAL_WAIT: "Tentative",
  CALENDAR_PAGE_CAL_STAY: "Waiting",
  CALENDAR_PAGE_CAL_NONE: "None",
  CALENDAR_PAGE_CAL_ALREADY_PASS: "Accepted",
  CALENDAR_PAGE_CAL_ALREADY_REJECT: "Rejected",
  CALENDAR_PAGE_CAL_SCHEDULE_TIME: "Metting Time: ",
  CALENDAR_PAGE_CAL_DELETE_EVENT: "Delete",
  CALENDAR_PAGE_CAL_INPUT_EVENT_NAME: "Please enter title",
  CALENDAR_PAGE_CAL_START_TIME: "Start Time",
  CALENDAR_PAGE_CAL_END_TIME: "End Time",
  CALENDAR_PAGE_CAL_EVENT: "Event",
  CALENDAR_PAGE_CAL_SURE_TRANSFER: "Confirm forwarding?",
  CALENDAR_PAGE_CAL_TRANSFER_FAIL: "Forwarded failed!",
  CALENDAR_PAGE_CAL_CHOOSE_REPEAT_COUNT: "Please select the repeat frequency",
  CALENDAR_PAGE_CAL_DELETE_EVENT_DESC: "This operation will permanently delete the event. Do you want to continue?",
  //login
  LOGIN_RULE1: "Please enter the answer", // 请输入安全问题的答案
  LOGIN_ERROR: "Abnormal login",

  //lockscreen
  LOCKSCREEN_TITLE: "Your webmail screen has been locked",
  LOCKSCREEN_MAILBOX_PASSWORD: "Password: ",

  //preview
  PREVIEW_DOWNLOAD_ATTACH: "Download",
  PREVIEW_MAIL_SUBJECT: "Mail Title: ",
  PREVIEW_VIEW_DESC: "Some part may not display correctly, please download to view",
  PREVIEW_ERROR: "Error: ",
  PREVIEW_RETRY: "retry",
  PREVIEW_OR: "Or directly",
  FILE_P_VIEW: " to view",
  PREVIEW_SURE_DOWNLOAD: "Are you sure to download the current file?",
  PREVIEW_LOADING_TEXT: "Loading... If the file is transcoded for a long time, you can check back later.",

  // lockscreen/twofactor_login 二次验证登录
  TWOFACTOR_LOGIN_TITLE: "Two-factor authentication",
  TWOFACTOR_LOGIN_RETURN: "Back",
  TWOFACTOR_LOGIN_GOOGLE: "Google Authentication",
  TWOFACTOR_LOGIN_SMS: "SMS Authentication",

  LOGIN_REMEMBER_USERNAME: "Remember username",
  //axios 页面
  AXIOS_LOGIN_ERROR: "The session has expired, please log in again!",
  AXIOS_SERVICE_ERROR: "Server error!",
  AXIOS_SYSTEM_ERROR: "System exception!",


  //用户注册 login/login
  REMARK_PAGE: "Collection",
  REGISTER_AGREEMENT: "Registration Agreement",
  USER_REGISTRATION: "Registration",
  REGISTER_AGREE: "Agree",
  REGISTER_PASSWORD: "Password",
  REGISTER_CONFIRM_PASSWORD: "Confirm Password",
  REGISTER_REALNAME: "Real Name",
  REGISTER_ENGNAME: "English Name",
  REGISTER_EENUMBER: "Job number",
  REGISTER_DEPARTMENT: "Department",
  REGISTER_BUTTON: "Registration",
  REGISTER_USERNAME_RULE: "Please enter your email",
  REGISTER_PASSWORD_RULE: "Please enter your password",
  REGISTER_CONFIRM_PASSWORD_RULE: "Please confirm your password",
  REGISTER_REALNAME_RULE:'Please enter your real name',
  REGISTER_DEPARTMENT_RULE: "Please select your department",

  COMMON_EXPORT:"export",
  //layout/index
  TITLE_DESC: " new mails arrived!",
  //login/login
  REGISTER_SUCCESS: " Registration successful! Please be patient and wait for approval, then you can use the application account to login!",
  COLECTION_NOTICE: "Please use Ctrl+D to bookmark this page.",

  //components/Contact  选择通讯录组件
  CHOOSE_CONTACT_DESC: "Please select department or member",
  CHOOSE_CONTACT_ALREADY: "Selected Departments or Members",

  // login/login login login page
  LOGIN_WELCOME:'Welcome to Webmail',
  LOGIN_USERNAME_RULE: "The user name format is incorrect!",
  LOGIN_PREV:'Previous',
  LOGIN_NEXT:'Next',
  LOGIN_FOR_USERNAME: "User Login",
  LOGIN_WY_DESC1: "Precision anti-spam, effective filtering over 98.6% of spam! ",
  LOGIN_WY_DESC2: "The effective interception rate of viral mail exceeds 99.9%! ",

  //layout/index mail full-text search
  LAYOUT_INDEX_KEYWORD: "Keyword contains",
  LAYOUT_INDEX_SUBJECT: "Subject contains",
  LAYOUT_INDEX_ATTACH: "Attach contains",
  LAYOUT_INDEX_MAILS: " ", // 的邮件
  LAYOUT_INDEX_MORE_SEARCH: "Advanced Search",
  LAYOUT_INDEX_LABEL_KEYWORD: "Keyword",
  LAYOUT_INDEX_LABEL_FOLDER: "Folder",
  LAYOUT_INDEX_LABEL_FOLDER_ROOT: "Root",
  LAYOUT_INDEX_LABEL_DATE: "Sent Time",
  LAYOUT_INDEX_NULL: "None",
  LAYOUT_INDEX_SEARCH_DATE1: "Yesterday",
  LAYOUT_INDEX_SEARCH_DATE2: "Past three days",
  LAYOUT_INDEX_SEARCH_DATE3: "Last Week",
  LAYOUT_INDEX_SEARCH_DATE4: "Last Month",
  LAYOUT_INDEX_SEARCH_DATE5: "Past three months",
  LAYOUT_INDEX_SEARCH_DATE6: "Past six months",
  LAYOUT_INDEX_SEARCH_DATE7: "Last Year",
  LAYOUT_INDEX_LABEL_SIZE: "Size",
  LAYOUT_INDEX_SIZE_DESC1: "0 ~ 100KB",
  LAYOUT_INDEX_SIZE_DESC2: "100kb ~ 10MB",
  LAYOUT_INDEX_SIZE_DESC3: "Over 10MB",
  LAYOUT_INDEX_SEARCH_RULES: "Keyword/Subject/Attach, fill in at least one!",
  LAYOUT_INDEX_SEARCH_TITLE: "Search Result",

  //mailbox/components/searchmail full-text search page
  MAILBOX_COM_SEARCH_CONDITION: "Search Conditions",
  MAILBOX_COM_SEARCH_NO:'Empty messages. The condition is ',
  MAILBOX_COM_SEARCH_FOLDER_DESC: "The scope of the folder where you are located",
  MAILBOX_COM_SEARCH_SENDER_DESC: "Sender is ",
  MAILBOX_COM_SEARCH_REC_DESC: "Recipient is ",
  MAILBOX_COM_SEARCH_DATE_DESC: "Sending time range",
  MAILBOX_COM_SEARCH_SIZE_DESC:'Mail size is',
  MAILBOX_COM_SEARCH_YOU_CAN:'You can',
  MAILBOX_COM_SEARCH_TIP1: "1. Replace keywords and search again",
  MAILBOX_COM_SEARCH_TIP2: "2. Use advanced search to search through other mail features",
  MAILBOX_COM_SEARCH_NOT_FOND: "Search mail does not exist or has been deleted!",

  //mailbox/innerbox not_spam
  MAILBOX_COM_INNERBOX_NOT_SPAM: "Not spam",
  MAILBOX_COM_INNERBOX_CONFIRM_1: "The message will be moved to the inbox",
  MAILBOX_COM_INNERBOX_CONFIRM_2: "Add the sender to whitelist",

  //mailbox/components/read.vue 查看邮件页面
  MAILBOX_COM_READ_PREV: "Last email",
  MAILBOX_COM_READ_NEXT: "Next email",

  //login/Login.vue 登录页面
  LOGIN_VERIFY_EXPLAIN: "Slide right to complete validation",
  LOGIN_VERIFY_SUCCESS: "Verification Pass",

  //calendar/page/calendar.vue 日程
  CALENDAR_FIXED_MODE: "Periodic mode",
  CALENDAR_MODE_DAILY: "Daily",
  CALENDAR_MODE_WEEKLY: "Weekly",
  CALENDAR_MODE_MONTHLY: "Monthly",
  CALENDAR_MODE_YEARLY: "Yearly",
  CALENDAR_DAY: "day",
  CALENDAR_REPEAT: "Repetition interval is",
  CALENDAR_AFTER_WEEK: "After Week",
  CALENDAR_MONTH: "Monthly",
  CALENDAR_MONTH_TH: " ",
  CALENDAR_FIRST: "First",
  CALENDAR_SECOND: "Second",
  CALENDAR_THIRD: "Third",
  CALENDAR_FOURTH: "Fourth",
  CALENDAR_LAST: "Last",
  CALENDAR_DAYS: "Days",
  CALENDAR_WORKDAYS: "Workday",
  CALENDAR_WEEKENDS: "Weekend",
  CALENDAR_AFTER_YEAR: "Year after",
  CALENDAR_JANUARY: "January",
  CALENDAR_FEBRUARY: "February",
  CALENDAR_MARCH: "March",
  CALENDAR_APRIL: "April",
  CALENDAR_MAY: "May",
  CALENDAR_JUNE: "June",
  CALENDAR_JULY: "July",
  CALENDAR_AUGUST: "August",
  CALENDAR_SEPTEMBER: "September",
  CALENDAR_OCTOBER: "October",
  CALENDAR_NOVEMBER: "November",
  CALENDAR_DECEMBER: "December",
  CALENDAR_DAYTH: "Day",
  CALENDAR_MONTHTH: "Month",
  CALENDAR_DE: "",
  CALENDAR_REPEAT_RANGE: "Duplicate Range",
  CALENDAR_NO_END: "No End Date",
  CALENDAR_END_TIMES: "time ended",
  CALENDAR_END_DAY: "End Date",
  CALENDAR_HAPPEN: "Occurs",
  CALENDAR_WEEK: "weekly",
  CALENDAR_START_DAY: "Effective Date",
  CALENDAR_END: "End",
  CALENDAR_OPEN_EVENT: "Open Periodic Projects",
  CALENDAR_SINGLE: "This project only",
  CALENDAR_ALL_EVENT: "Whole Sequence",
  CALENDAR_EVENT_EDIT_PLAIN: "'Here only the whole sequence can be modified!",

  CALENDAR_TIPS: "Repetition times must be greater than 0!",

  //个人网盘文件分享 views/contact/pab.vue
  FILE_SHARE: 'share',
  FILE_SHARE_TITLE: 'Share File',
  FILE_SHARE_DESC: 'Create share link, share file with your friends.',
  FILE_SHARE_CREATE_LINK: 'Create Links',
  FILE_SHARE_CREATE_SUC: 'Create share link successfully ！',
  FILE_SHARE_CANCEL_SHARE: 'Cancel share',
  FILE_SHARE_LINK: 'Link ',
  FILE_SHARE_CODE: 'Code ',
  FILE_SHARE_COPY_SUC: 'Share link copied',
  FILE_SHARE_COPY_FAIL: 'Share link copied error',
  FILE_SHARE_COPY_SHARE: 'Copy link and code to share with your friends',
  FILE_SHARE_COPY: 'Copy link and code',
  FILE_SHARE_CREATE_FAIL: 'Create share link fail !',
  FILE_SHARE_CANCEL_SUC: 'Cancel share successfully!',
  FILE_SHARE_CANCEL_FAIL: 'Cancel share fail !',

  //文件提取页面  views/fileshare.vue
  SHARE_FROM: ' share file with you',
  SHARE_CANCEL: 'share file has been cancelled',
  SHARE_CODE_ERR: 'share code error',
  SHARE_INPUT_CODE: 'please input share code',
  SHARE_DOWNLOAD: 'Download',

  //名片 mailbox/components/read.vue
  EDIT_CONTACT: 'Edit Contact',
  ADD_TO_CONTACT: 'Add to Address Book',
  REFUSE_EMAIL: 'Block Sender',
  ADD_TO_WHITE: 'White List',
  CURRENT_MAIL: 'Related Mail',

  //文件夹和标签 setting/page/tag.vue
  FOLDER_AND_TAG: "Folders and Labels",
  FOLDER: "Folder",
  ALL_MAILS: "Total Number of Mails",
  CLEAR_FOLDERS: "Empty",
  ADD_TAG: "Add tags",
  MAIL_TAG: "Mail label",
  TAG_NAME: "Label name",
  TAG_COLOR: "Label color",
  PICK_COLOR: "Select color",
  EDIT_TAG: "Modify label",
  TAG_NAME_RULE: "Please enter the label name",
  CANCEL_TAG: "Cancel label",
  DARK_GRAY: "Dark grey",
  TAG: "Label",
  CANCEL_ALL_TAG: "Cancel all labels",
  CREATE_TAG_ADD: "New label and label",
  ORDER: "Ascending order",
  ORDER_DESC: "Descending order",
  TAG_TITLE: "Click to view the mail containing this tag",

  //查看邮件页面 mailbox/components/read.vue
  READ_RETURN_PATH: "The real sending address is inconsistent with the declared sender's address. Please carefully examine the authenticity of the contents of the mail.",
  RETURN_PATH_BY: "E-mail from",
  RETURN_PATH: "",

  CLEAR_TEMPLATE: "Empty template letters",
  CLEAR_SIGNATRUE: "Empty signature",
  CLEAR_WHITER: "Clear List",
  CLEAR_BLACKER: "Clear the Blacklist",
  CLEAR_TEMPLATE_DES: "Clear all template letters?",
  CLEAR_SIGNATRUE_DES: "Clear all signatures?",
  CLEAR_WHITER_DES: "Clear all blank lists?",
  CLEAR_BLACKER_DES: "Clear all blacklists?",
  BDELETE_TEMPLATE_DES: "Batch deletion of selected template letters?",
  BDELETE_SIGNATRUE_DES: "Batch deletion of selected signatures?",
  BDELETE_WHITER_DES: "Batch deletion of the selected white list?",
  BDELETE_BLACKER_DES: "Batch deletion of selected blacklists?",
  BDELETE_RE_DES: "Batch deletion of selected items?",
  SEARCH_TABLE_BTN: "Find in the List",

  BATCH_DISABLED: "Batch disable",
  BATCH_ENABLE: "Batch enabled",
  BATCH_DISABLED_DESC: "Batch Disabled Selected Items?",
  BATCH_ENABLE_DESC: "Batch Enablation of Selected Items?",

  DELETE_FOLDER: "remove folders",
  IS_DELETE_FOLDER: "Whether to delete folders",
  MAIL_MOVE_TO: "Your mail will be moved to",
  CHOOSE_FOLDER: "Please select folders",
  CLEAR_FOLDER_DESC: "Mail in this folder will be emptied and cannot be restored.",
  ALSO_DEL_MAIL: "Delete mail at the same time",

  ARIVAL_DESC: "Time of arrival of mail：",
  UPLOAD_PAUSE: "Pause",
  UPLOAD_RESUME: "Continue",
  UPLOAD_CANCEL: "Cancel",
  IMPORT_MAILS: "Incoming mail",
  IMPORT_MAILS_MSG: " is not mail",

  FILE_MAIL_MSG: "Upload failed! Uploading files has exceeded the capacity of personal mailbox!",
  REMARK: "Remarks Information",
  ADD_REMARK: "Mail notes",
  REMARK_MSG: "Please enter a note!",
  REMARK_MSG2: "No more than 200 characters!",
  REMARK_DELETE_DESC: "Are you sure you want to delete this email comment?",

  SAME_SUBJECT_SEARCH: "View with the same theme",
  NO_FOLDER_DESC: "The folder in which this message is located does not exist or has been deleted!",
  EDIT: "Edit",
  SELECT_TAG: "Select Mail Tags",

  SSL_LOGIN: "SSL Login",
  DEEP_DELETE: "After deletion, the mail will not be restored. Are you sure you want to delete it?",
  ALREADY_SHARE: "Already shared",
  INFINITE: "Infinite",

  IS_OPENED: "Opened",
  IS_CLOSED: "Closed",
  OPEN: "Open",
  CLIENT_LOGIN: "Client Tools Log in with Mobile Authorized Password",
  NO_OPEN_CLIENT_LOGIN: "Unopened Client Tool Logs in with Mobile Authorized Password",
  IS_OPENED_CLIENT_LOGIN: "Client tools have been opened to log in using mobile phone authorized passwords",
  OPEN_CLIENT_LOGIN: "Open Client Login",
  OPEN_IMAP: "Open IMAP/SMTP",
  CLIENT_DESC: 'Successfully open the "Client Tool Uses Mobile Phone Authorized Password Logon"service; when the third party client logs in, please enter the following authorization code:',
  CLIENT_TIPS: 'Warm Tip: When you log in to a third party client, please enter"Authorization Code"in the password box for verification. ',
  RELEASE_CLIENT: "Determine to remove the client login authorization code?",

  LOGIN_OVERTIME_TIPS: "The session expiration time for any continuous operation on the interface.",
  SENT_SAME_TO: "Send new mail to the same recipient",

  READ_TYPE_TIPS: '"Read Pure Text Content (T)"form to view the current mail; if you need to switch permanently to"Read Hypertext Content (H)", please go to ',
  SET_PARAMS: "Parameter Settings",

  CHECK_CODE: "Verification code failed, please re-validate!",
  ANOTHER_PIC: "Change one",
  CHECK_CODE_XUANZI: "Please click in sequence",
  MORE_TO: "This email is a mass email. Do you want to continue sending it?",

  SECLEVEL: "SecLevel:",
  SECLEVEL_NORMAL: "Non-secret",
  SECLEVEL_INTERNAL: "Internal",
  SECLEVEL_SECRET: "Secret",
  SECLEVEL_PRIVACY: "Confidential",
  SECLEVEL_HIGHEST: "Top-secret",

  IS_BURN_MAIL_CLOSE_DESC: "This email will be burned after reading, and will be destroyed automatically after closing! Confirm closure?",
  IS_BURN_MAIL_CLOSEALL_DESC: "Closed email contains email burning after reading, and will be destroyed automatically after closing! Confirm closure?",

  BURN_LEFT: "Remaining Reading Number",
  BURN_DAY: "Destruction Time",
  SELECT_MAIL_SECRET: "Please select the mail encryption level",
  SELECT_ATTACH_SECRET: "Please select the attachment secret level",
  ATTACH_HIGHER_MAIL: "Attachment security level cannot be higher than mail security level",
  SAVE_DRAFT_DESC: "At least any content, theme or attachment is not empty before it can be saved as a draft.",
  CHANGE_PASSWORD: "Successful password modification, please login with the new password",

  UPLOAD_DES: "Please click on the upload file or drag the file to this area to add attachments",
  UPLOAD_DES_FILE: "Please click on the upload file or drag the file to this area for upload",
  USERNAME_DESC: "User names can only contain numbers or lowercase letters!",

  POP_FOLDER: "Storage folder",
  POP_KEEPMAIL: "Mail Backup in the Original Mailbox",

  IMPORT_MAIL: "Support the import of regular EML mail",

  ATTACH_LOG: "Download Records",
  ATTACH_LOG_TIME: "Download Time",
  ATTACH_LOG_REC: "Downloader",
  ATTACH_LOG_TIMES: "Download times",
  ATTACH_LOG_SEARCH: "Download Record Query",

  WEBMAIL_ATTACHMENT_EXPIRED: "The expiration time of Mail Online attachments",
  COMMON_ONE_MONTH: "One month",
  COMMON_TWO_MONTH: "Two months",
  COMMON_THREE_MONTH: "One Quarter",
  COMMON_HALF_YEAR: "Half a Year",
  COMMON_ONE_YEAR: "One Year",

  IS_ONLINE_ATTACH: "Online Accessories",

  WECHART_BIND: "Wechat Binding",
  BINDED_WECHART: "Wechat is currently bound：",
  WECHART_BIND_DESC: "after binding, you can use WeChat login webmail directly",
  BINDED: "Binded",
  UNBOUND: "Unbound",
  NO_BOUND: "Unbound",
  BOUND_ACTION: "Binding",
  SURE_UNBOUND: "Determine to unbind?",

  DEFAULT_FOLDER: "System Folder",
  WECHART_LOGIN: "WECHART Login",

  CLEAR_UPLOAD_LIST: "Clear List",
  NO_SAVE_ATTACH: "Webmail sent without attachments saved",
  NO_SAVE_ATTACH_DESC: "Mails less than 1M are saved only, and text is saved only when they are larger than 1M.",

  ATTACH_DOWNLOAD: "Click Download",
  DOWNLOAD_ADDRESS: "Download Address",
  ATTACH_MAX_DESC1: "Attachments exceed",
  ATTACH_MAX_DESC2: "Please transfer to online attachment mode to send",
  TRANSFER_ATTACH: "Transfer to Online Accessories",
  TRANSFER_MAX_DESC: "Note: The size of a single attachment exceeds 30M. It is recommended that the attachment be sent online.",
  TRANSFER_ATTACH_ALL: "All on-line accessories",
  MY_FOLDER: "My Folder",

  MAILBOX_LOCK: '"My Folderis" locked and protected. Password authentication is required to enter this area.',
  CANLENDAR_LOCK: '"My calendar"is locked and protected. Password verification is required to enter this area.',
  FILE_LOCK: '"File Center"is locked and protected. Password authentication is required to enter the area. ',
  CANCEL_LOCK: "cancel locking ",
  INPUT_PWD: "Please enter your password:",
  ADMIN_CANCEL_PWD: "Please contact the administrator to cancel the password!",
  SET_LOCK_PWD: "Set Password:",
  SET_LOCK: "File Center Lock Settings",
  PWD_AGAIN: "Retransmit Password:",
  LOCK_PRO: "Select Lock Protection Range:",
  SURE_LOCK: "Determine Locking",
  LOCK_DESC: 'Lock"My Folder","My Schedule"and"Document Center"to make it safer.',
  LOCK_SOON: "Lock immediately",
  IS_LOCK: "You have set the lock,",
  EDIT_LOCK: "Modify Lock Settings",
  EDIT_LOCK_DESC: "Please complete the password! If you do not change your password, please do not fill in.",
  SRC_PWD: "Original password：",

  WEBMAIL_SHOW_SRCMAILNAME: "use address book name",
  WEBMAIL_SHOW_SRCMAILNAME_HELP: "if the addressee is in the address book, use the address book name and do not open by default.",

  DST_FOLDER: "move to location",

  MAILBOXMOVE_DESC: "the system has just been migrated, so you need to maintain the mailbox to move. Or the verification of the mobile account of the email failed. Please modify the settings. ",
  MAILBOXMOVE_TITLE: "warm prompt",

  RECEIPT: "Receipt",

}
export default zh_hans;
